import type { ChoiceDrillItem } from "@/components/simulators/SimulatorRegistry";

export const LINUX_PACKAGE_POOL: ChoiceDrillItem[] = [
  {
    id: "pkg-apt-update",
    prompt: "On Debian/Ubuntu, refresh the local package index from repositories.",
    choices: [
      { id: "a", text: "sudo apt update" },
      { id: "b", text: "sudo apt upgrade" },
      { id: "c", text: "sudo apt install update" },
      { id: "d", text: "sudo yum update" },
    ],
    correctChoiceId: "a",
    weakConcept: "apt update vs upgrade",
    explanation: "apt update downloads index metadata; upgrade installs newer packages.",
  },
  {
    id: "pkg-apt-install",
    prompt: "Install the curl package on Ubuntu.",
    choices: [
      { id: "a", text: "sudo apt install curl" },
      { id: "b", text: "sudo apt get curl" },
      { id: "c", text: "sudo dnf install curl" },
      { id: "d", text: "sudo snap curl" },
    ],
    correctChoiceId: "a",
    weakConcept: "apt install syntax",
    explanation: "apt install retrieves and installs the named package and dependencies.",
  },
  {
    id: "pkg-dnf-install",
    prompt: "Install nginx on a RHEL 9 / Fedora system using DNF.",
    choices: [
      { id: "a", text: "sudo dnf install nginx" },
      { id: "b", text: "sudo apt install nginx" },
      { id: "c", text: "sudo yum-get nginx" },
      { id: "d", text: "sudo rpm install nginx" },
    ],
    correctChoiceId: "a",
    weakConcept: "dnf package management",
    explanation: "DNF is the default package manager on modern RHEL/Fedora systems.",
  },
  {
    id: "pkg-rpm-query",
    prompt: "Check whether the openssh-server package is installed via RPM database.",
    choices: [
      { id: "a", text: "rpm -q openssh-server" },
      { id: "b", text: "rpm -i openssh-server" },
      { id: "c", text: "dnf -q openssh-server" },
      { id: "d", text: "which openssh-server" },
    ],
    correctChoiceId: "a",
    weakConcept: "rpm query",
    explanation: "rpm -q queries installed packages; -i installs (different flag meaning).",
  },
  {
    id: "pkg-apt-remove",
    prompt: "Remove the telnet package but keep configuration files on Debian/Ubuntu.",
    choices: [
      { id: "a", text: "sudo apt remove telnet" },
      { id: "b", text: "sudo apt purge telnet" },
      { id: "c", text: "sudo apt delete telnet" },
      { id: "d", text: "sudo dnf erase --keep-config telnet" },
    ],
    correctChoiceId: "a",
    weakConcept: "apt remove vs purge",
    explanation: "remove uninstalls the package; purge also removes configuration files.",
  },
  {
    id: "pkg-dnf-search",
    prompt: "Search repository metadata for packages related to 'postgresql' on DNF systems.",
    choices: [
      { id: "a", text: "dnf search postgresql" },
      { id: "b", text: "dnf find postgresql" },
      { id: "c", text: "rpm search postgresql" },
      { id: "d", text: "apt search postgresql" },
    ],
    correctChoiceId: "a",
    weakConcept: "dnf search",
    explanation: "dnf search queries package names and summaries in enabled repos.",
  },
  {
    id: "pkg-apt-list",
    prompt: "List all installed packages on a Debian-based system.",
    choices: [
      { id: "a", text: "apt list --installed" },
      { id: "b", text: "apt show --all" },
      { id: "c", text: "dpkg -l (also valid)" },
      { id: "d", text: "Both a and c are common correct approaches" },
    ],
    correctChoiceId: "d",
    weakConcept: "Listing installed packages",
    explanation: "apt list --installed and dpkg -l both show installed Debian packages.",
  },
  {
    id: "pkg-dnf-update",
    prompt: "Update all installed packages to latest versions in enabled repos (RHEL/Fedora).",
    choices: [
      { id: "a", text: "sudo dnf upgrade" },
      { id: "b", text: "sudo dnf update only refreshes metadata" },
      { id: "c", text: "sudo yum refresh all" },
      { id: "d", text: "sudo rpm -U all" },
    ],
    correctChoiceId: "a",
    weakConcept: "dnf upgrade",
    explanation: "dnf upgrade installs available updates for installed packages.",
  },
  {
    id: "pkg-which-mgr",
    prompt: "A server runs Red Hat Enterprise Linux 8. Default package manager?",
    choices: [
      { id: "a", text: "yum or dnf (dnf preferred on RHEL 8+)" },
      { id: "b", text: "apt" },
      { id: "c", text: "pacman" },
      { id: "d", text: "zypper only" },
    ],
    correctChoiceId: "a",
    weakConcept: "Distro package manager mapping",
    explanation: "RHEL/CentOS/Fedora family uses RPM with yum/dnf frontends.",
  },
  {
    id: "pkg-security-update",
    prompt: "Install only security updates on Ubuntu with unattended-upgrades alternative manual approach.",
    choices: [
      { id: "a", text: "sudo apt install -s $(apt list --upgradable 2>/dev/null | grep security) or use apt upgrade with security pocket" },
      { id: "b", text: "sudo apt install security-updates meta-package always exists" },
      { id: "c", text: "Security updates require manual kernel compile" },
      { id: "d", text: "Use dnf security-only on Ubuntu" },
    ],
    correctChoiceId: "a",
    weakConcept: "Security patching on Debian",
    explanation: "Ubuntu security updates come from the -security pocket; filter or use unattended-upgrades.",
  },
];
