import type { ChoiceDrillItem } from "@/components/simulators/SimulatorRegistry";

export const LINUX_SYSTEMD_POOL: ChoiceDrillItem[] = [
  {
    id: "sysd-status",
    prompt: "Which command shows detailed status of the nginx service including recent logs?",
    choices: [
      { id: "a", text: "systemctl status nginx" },
      { id: "b", text: "service nginx --logs" },
      { id: "c", text: "journalctl start nginx" },
      { id: "d", text: "systemd-run nginx status" },
    ],
    correctChoiceId: "a",
    weakConcept: "systemctl status",
    explanation: "systemctl status shows load state, active state, and recent journal entries for a unit.",
  },
  {
    id: "sysd-journal-unit",
    prompt: "View all logs for the sshd unit since today. Best command?",
    choices: [
      { id: "a", text: "journalctl -u sshd --since today" },
      { id: "b", text: "cat /var/log/sshd.log" },
      { id: "c", text: "systemctl log sshd" },
      { id: "d", text: "dmesg -u sshd" },
    ],
    correctChoiceId: "a",
    weakConcept: "journalctl unit filtering",
    explanation: "journalctl -u filters by systemd unit; --since limits the time range.",
  },
  {
    id: "sysd-enable",
    prompt: "Enable apache2 to start automatically at boot on a systemd system.",
    choices: [
      { id: "a", text: "systemctl enable apache2" },
      { id: "b", text: "systemctl start apache2" },
      { id: "c", text: "chkconfig apache2 on" },
      { id: "d", text: "systemctl autostart apache2" },
    ],
    correctChoiceId: "a",
    weakConcept: "enable vs start",
    explanation: "enable creates symlinks for boot; start runs the service immediately.",
  },
  {
    id: "sysd-restart",
    prompt: "Restart the fail2ban service after config change.",
    choices: [
      { id: "a", text: "systemctl restart fail2ban" },
      { id: "b", text: "systemctl reload fail2ban only always sufficient" },
      { id: "c", text: "service fail2ban reboot" },
      { id: "d", text: "systemctl refresh fail2ban" },
    ],
    correctChoiceId: "a",
    weakConcept: "systemctl restart",
    explanation: "restart stops and starts the unit; reload works only if the unit supports it.",
  },
  {
    id: "sysd-journal-priority",
    prompt: "Show only error-level and above messages from the journal.",
    choices: [
      { id: "a", text: "journalctl -p err" },
      { id: "b", text: "journalctl --level error-only" },
      { id: "c", text: "systemctl errors" },
      { id: "d", text: "dmesg -e" },
    ],
    correctChoiceId: "a",
    weakConcept: "journalctl priority filter",
    explanation: "-p err shows err, crit, alert, and emerg priority messages.",
  },
  {
    id: "sysd-list-failed",
    prompt: "List units that failed to start.",
    choices: [
      { id: "a", text: "systemctl --failed" },
      { id: "b", text: "systemctl list errors" },
      { id: "c", text: "journalctl --failed" },
      { id: "d", text: "systemd-analyze failed" },
    ],
    correctChoiceId: "a",
    weakConcept: "Failed unit troubleshooting",
    explanation: "systemctl --failed lists units in failed state for quick diagnosis.",
  },
  {
    id: "sysd-follow",
    prompt: "Follow live journal output (like tail -f) for all messages.",
    choices: [
      { id: "a", text: "journalctl -f" },
      { id: "b", text: "journalctl --live" },
      { id: "c", text: "systemctl follow" },
      { id: "d", text: "tail -f /var/log/journal" },
    ],
    correctChoiceId: "a",
    weakConcept: "journalctl follow mode",
    explanation: "journalctl -f follows new entries as they are written.",
  },
  {
    id: "sysd-mask",
    prompt: "Prevent a unit from being started manually or as a dependency (stronger than disable).",
    choices: [
      { id: "a", text: "systemctl mask unitname" },
      { id: "b", text: "systemctl hide unitname" },
      { id: "c", text: "systemctl block unitname" },
      { id: "d", text: "systemctl deny unitname" },
    ],
    correctChoiceId: "a",
    weakConcept: "mask vs disable",
    explanation: "mask links unit files to /dev/null, preventing all starts until unmasked.",
  },
  {
    id: "sysd-boot-time",
    prompt: "Analyze systemd boot time and slow-starting units.",
    choices: [
      { id: "a", text: "systemd-analyze blame" },
      { id: "b", text: "systemctl boot-time" },
      { id: "c", text: "journalctl --boot-time" },
      { id: "d", text: "dmesg --analyze" },
    ],
    correctChoiceId: "a",
    weakConcept: "systemd-analyze",
    explanation: "systemd-analyze blame lists units ordered by initialization time.",
  },
  {
    id: "sysd-journal-boot",
    prompt: "Show logs from the previous boot (not current).",
    choices: [
      { id: "a", text: "journalctl -b -1" },
      { id: "b", text: "journalctl --previous" },
      { id: "c", text: "systemctl logs --last-boot" },
      { id: "d", text: "cat /var/log/boot.old" },
    ],
    correctChoiceId: "a",
    weakConcept: "journalctl boot index",
    explanation: "journalctl -b -1 selects the boot entry immediately before the current boot.",
  },
];
