export type PianoTeachingContent = {
  explanation: string;
  steps: string[];
  listenNotes?: number[];
  listenLabel?: string;
  listenDurationsMs?: number[];
  notice?: string;
  physicalCheck?: string[];
};

export const PIANO_LESSON_TEACHING: Record<string, PianoTeachingContent> = {
  "one-white-key": { explanation: "A piano key is a lever you press to begin a sound. White keys are the long keys at the front—the easiest surface to reach.", steps: ["Look at the single bright key.", "Press it once and listen until the sound fades.", "Release without lifting your whole hand."], notice: "For now, the goal is simply to connect one movement with one sound." },
  "white-key-field": { explanation: "White keys form the lower, repeating pathway across the instrument. They are different pitches, but they share the same shape and color.", steps: ["Choose any white key.", "Try one farther left and one farther right.", "Notice that moving right sounds higher; moving left sounds lower."], notice: "The black keys are temporarily hidden so the white-key field is easy to see." },
  "black-key-groups": { explanation: "The shorter black keys sit above the white keys. They repeat in groups of two, then three—your first reliable keyboard map.", steps: ["Play one black key from a group of two.", "Play one from a group of three.", "Scan the keyboard and find the next two–three grouping."], notice: "You will navigate by these groups instead of counting from the end of the keyboard." },
  "c-landmark": { explanation: "C is the white key immediately to the left of every group of two black keys. It is useful because the pattern makes it fast to find anywhere.", steps: ["Find a group of two black keys.", "Move to the white key directly left of them.", "Play that C, then find another C higher or lower."], notice: "C is not more musical than the other notes; it is simply our first landmark." },
  "natural-family": { explanation: "The seven white-key names are C, D, E, F, G, A, and B. After B, the names begin again at C.", steps: ["Start on Middle C—the labeled C near the center.", "Move right one white key at a time while reading the names.", "Finish on the next C and listen for the sense of arrival."], listenNotes: [60,62,64,65,67,69,71,72], listenLabel: "Hear C through C", notice: "These eight played keys contain seven different note names; the last C begins the next repetition." },
  "octave-pattern": { explanation: "Two notes with the same letter name, twelve keys apart, form an octave. They sound like the same identity at different heights.", steps: ["Find Middle C using the group of two.", "Find the next group of two to the right.", "Play its C and compare the two sounds."], listenNotes: [60,72], listenLabel: "Hear the two Cs", notice: "This repeating identity is why a large piano can be understood as one small pattern." },

  "c-fluency": { explanation: "A landmark becomes useful when you can find it without counting. Every group of two black keys points to a C on its left.", steps: ["Look away from the letter labels if you can.", "Choose any group of two black keys.", "Play the white key immediately to its left."], notice: "Any octave is correct in this exercise." },
  "neighbors-of-c": { explanation: "Notes are easier to learn as relationships. D is the white key immediately right of C; B is immediately left.", steps: ["Find Middle C.", "Step left to B, return to C, then step right to D.", "Play B–C–D as one three-note shape."], listenNotes: [59,60,62], listenLabel: "Hear B–C–D", notice: "This is the beginning of reading intervals as movement rather than isolated labels." },
  "f-landmark": { explanation: "F begins the other black-key group. It is the white key immediately to the left of every group of three black keys.", steps: ["Find three black keys together.", "Move to the white key immediately left.", "Play F, then locate another F by the same rule."], notice: "C and F together give you two landmarks inside every octave." },
  "natural-navigation": { explanation: "Now use C and F as anchors. Nearby notes can be found by one or two steps instead of counting all seven names.", steps: ["Find F from the group of three.", "Find A inside that same region.", "Then locate D and B relative to the nearest C."], notice: "Pause before each note and name the landmark you used." },
  "higher-lower": { explanation: "Pitch describes how high or low a sound feels. On the piano, moving right raises pitch and moving left lowers it.", steps: ["Play C–E–G and hear the line rise.", "Then play E–D–C and hear it fall.", "Watch the keyboard motion while listening to the contour."], listenNotes: [60,64,67,64,62,60], listenLabel: "Hear rise and fall", notice: "This shape—called contour—will become part of melody and notation." },
  "sharp-flat-neighbor": { explanation: "The black key between C and D can be described from either neighbor: C sharp means C raised; D flat means D lowered.", steps: ["Play C, the black key, then D.", "Hear that the black key is the smallest move from either side.", "Play the black key by itself to complete the check."], listenNotes: [60,61,62], listenLabel: "Hear C–C♯/D♭–D", notice: "Two names can describe one physical key because musical spelling depends on direction and context." },

  "relaxed-setup": { explanation: "Good setup makes movement easier; it does not force one rigid pose. Adjust until your shoulders, elbows, wrists, and fingers can move without strain.", steps: ["Sit near the front half of a stable bench or chair.", "Set the height so your forearms are roughly level with the keys.", "Move close enough that your elbows rest slightly in front of your body—not pinned behind you.", "Let your shoulders drop and place curved, unforced fingers on five neighboring keys."], physicalCheck: ["Feet supported", "Shoulders loose", "Wrists neither collapsed nor forced upward", "No pain, numbness, or held breath"], notice: "ReLearn cannot see or certify your technique. Stop and adjust if anything hurts." },
  "one-finger-control": { explanation: "A controlled note has a clear beginning and ending. Use a small finger movement while the rest of the hand remains easy.", steps: ["Rest one finger on Middle C before pressing.", "Lower the key without striking from far above.", "Hold briefly, release, and notice the key return."], notice: "MIDI verifies the press and release timing—not which finger you used or whether your hand was relaxed." },
  "five-note-walk": { explanation: "Place five neighboring fingers over C–D–E–F–G. Each finger gets one nearby key so the hand does not have to jump.", steps: ["Begin with your thumb on Middle C if using the right hand.", "Play C–D–E–F–G slowly, one note at a time.", "Keep every motion small and pause if tension appears."], listenNotes: [60,62,64,65,67], listenLabel: "Hear the five-note walk", notice: "Correct notes are evidence of navigation, not proof of fingering or healthy movement." },
  "return-home": { explanation: "Descending reverses the route but feels different to the hand. Treat it as its own coordination skill.", steps: ["Begin on G with the five-finger position still resting.", "Play G–F–E–D–C without rushing.", "Let C feel like the destination."], listenNotes: [67,65,64,62,60], listenLabel: "Hear the return", notice: "If the hand tightens, stop, reset its resting shape, and continue more slowly." },
  "five-note-riff": { explanation: "A riff is a short recognizable musical idea. This one rises, skips to G, and returns home.", steps: ["Listen once before playing.", "Play C–D–E–G, then E–D–C.", "Repeat it and try to preserve the same unhurried pulse."], listenNotes: [60,62,64,67,64,62,60], listenLabel: "Hear the riff", notice: "This is music, not only finger preparation: direction and repetition give the notes a shape." },

  "feel-pulse": { explanation: "Pulse is the steady underlying beat you could nod or walk to. The notes may change while the pulse continues.", steps: ["Listen to four evenly spaced clicks.", "Keep counting 1–2–3–4 after they stop.", "Tap one key four times without changing that spacing."], listenNotes: [60,60,60,60], listenLabel: "Hear four steady beats", listenDurationsMs: [500,500,500,500], notice: "Accuracy means consistent spacing, not speed." },
  "four-beat-groups": { explanation: "Music often organizes pulse into repeating groups. Counting four gives each beat a position: 1, 2, 3, 4—then 1 again.", steps: ["Count aloud with the example.", "Give beat 1 a little mental emphasis.", "Play two groups of four while the count repeats."], listenNotes: [60,60,60,60,60,60,60,60], listenLabel: "Hear two groups of four", listenDurationsMs: [500,500,500,900,500,500,500,500], notice: "The longer gap in the exercise marks the breath between groups, not a lost beat." },
  "long-short": { explanation: "Rhythm includes duration: how long a sound continues. A held note occupies more time than a short note even if both begin on a beat.", steps: ["Press Middle C and keep it down.", "Count slowly while the sound continues.", "Release after about two seconds and listen to the ending."], notice: "The note-off message lets MIDI measure duration truthfully." },
  "quarter-half": { explanation: "At a steady pulse, a quarter note lasts one beat and a half note lasts two. The names describe duration—not volume or pitch.", steps: ["Count 1–2–3–4 evenly.", "Play short C notes on counts 1 and 2.", "Play C on count 3 and hold it through count 4."], listenNotes: [60,60,60], listenLabel: "Hear short, short, long", listenDurationsMs: [500,500,1000], notice: "Keep the pulse unchanged while the final note lasts longer." },
  "copy-rhythm": { explanation: "Rhythmic listening means remembering the spaces between attacks. Use one pitch so your attention can stay on time.", steps: ["Listen to short–short–long.", "Hold the pattern silently in your body.", "Copy it on any single key, then compare."], listenNotes: [60,60,60], listenLabel: "Hear the rhythm", listenDurationsMs: [350,350,700], notice: "If the spacing drifts, listen again and restart rather than speeding through the correction." },

  "c-major-sound": { explanation: "A scale is an ordered family of pitches. C major uses the white keys from C to the next C and has a bright, settled sound you will soon learn to construct.", steps: ["Listen without playing the first time.", "Notice the final C feels related to the first, but higher.", "Play freely among C, D, E, and G and listen for how C feels like home."], listenNotes: [60,62,64,65,67,69,71,72], listenLabel: "Hear C major", notice: "First hear the family; the next lessons explain the distances that create it." },
  "whole-half": { explanation: "A half step moves to the very next key, black or white. A whole step crosses over one key and lands on the following key.", steps: ["Play C then C♯: no key lies between them, so that is a half step.", "Return to C, then play D: C♯ lies between, so that is a whole step.", "Compare the smaller and larger sound distances."], listenNotes: [60,61,60,62], listenLabel: "Compare half and whole steps", notice: "On the keyboard, E–F and B–C are half steps even though both keys are white." },
  "build-major": { explanation: "Every major scale follows the same distance pattern: whole, whole, half, whole, whole, whole, half. Starting on C, that pattern lands on white keys only.", steps: ["C→D whole; D→E whole; E→F half.", "F→G whole; G→A whole; A→B whole.", "B→C half. Play the complete route and say the distances if helpful."], listenNotes: [60,62,64,65,67,69,71,72], listenLabel: "Hear the major pattern", notice: "The white keys are not the definition of major—the whole/half-step pattern is." },
  "c-major-up-down": { explanation: "Now practice the scale as one continuous route. Ascending and descending are separate coordination skills; neither needs speed yet.", steps: ["Start on Middle C and play to C5.", "Play C5 again only if you need to reset your sense of direction.", "Return through B–A–G–F–E–D to Middle C."], listenNotes: [60,62,64,65,67,69,71,72,71,69,67,65,64,62,60], listenLabel: "Hear the complete route", notice: "This exercise verifies pitch order. Fingering instruction and physical review remain separate." },
  "scale-degrees": { explanation: "Scale-degree numbers describe each note’s role relative to home. In C major: C is 1, D is 2, E is 3, and G is 5.", steps: ["Play C (1) and hear stability.", "Try D (2) or G (5), then return to C and notice the pull resolve.", "Create a short idea using only C, D, E, and G; finish on C if you want a settled ending."], listenNotes: [60,62,64,67,62,60], listenLabel: "Hear away and home", notice: "There is more than one valid melody. ReLearn checks the available note set, not whether your musical choice is the only correct one." },
};
