import type { PerformanceExercise } from "@/lib/interactive-learning/types";

export const PIANO_FOUNDATIONS_LESSONS = [
  { id: "keyboard", number: 1, title: "Meet the Keyboard", state: "active" },
  { id: "notes", number: 2, title: "Learn the Notes", state: "active" },
  { id: "hands", number: 3, title: "Your Hands", state: "active" },
  { id: "rhythm", number: 4, title: "Pulse and Rhythm", state: "planned" },
  { id: "scales", number: 5, title: "Scales and Scale Degrees", state: "planned" },
  { id: "melodies", number: 6, title: "Melodies", state: "planned" },
  { id: "chords", number: 7, title: "Chords", state: "planned" },
  { id: "progressions", number: 8, title: "Chord Progressions", state: "planned" },
  { id: "two-hands", number: 9, title: "Two-Hand Coordination", state: "planned" },
  { id: "reading", number: 10, title: "Reading Music", state: "planned" },
  { id: "expression", number: 11, title: "Expression", state: "planned" },
  { id: "piece", number: 12, title: "First Complete Piece", state: "planned" },
  { id: "grey-key", number: 13, title: "The Grey Key", state: "mastery-locked" },
] as const;

export const PIANO_PATTERN_EXERCISES: PerformanceExercise[] = [
  {
    id: "first-signal",
    kind: "play-set",
    prompt: "Play any key. ReLearn will show you what the keyboard sent.",
  },
  {
    id: "find-c",
    kind: "play-pitch-class",
    prompt: "Find a C. Play any C on your keyboard.",
    hint: "C is the white key immediately to the left of a group of two black keys.",
    targetPitchClasses: [0],
  },
  {
    id: "find-another-c",
    kind: "play-pitch-class",
    prompt: "Find another C—higher or lower than the first one.",
    hint: "Look for the same two-black-key landmark somewhere else.",
    targetPitchClasses: [0],
  },
];

export const PIANO_FOUNDATIONS_UNITS = [
  { id: "keyboard", title: "Meet the Keyboard", outcome: "See one repeating twelve-note pattern.", status: "playable" },
  { id: "notes", title: "Learn the Notes", outcome: "Navigate natural notes and nearby sharps or flats.", status: "playable" },
  { id: "hands", title: "Your Hands", outcome: "Develop relaxed, deliberate physical control.", status: "designed" },
  { id: "rhythm", title: "Pulse and Rhythm", outcome: "Feel, copy, and maintain a steady pulse.", status: "designed" },
  { id: "scales", title: "Scales and Scale Degrees", outcome: "Build and hear ordered note families.", status: "designed" },
  { id: "melodies", title: "Melodies", outcome: "Play and reshape short musical ideas.", status: "designed" },
  { id: "chords", title: "Chords", outcome: "Build and recognize useful triads.", status: "designed" },
  { id: "progressions", title: "Chord Progressions", outcome: "Connect chords into musical motion.", status: "designed" },
  { id: "two-hands", title: "Two-Hand Coordination", outcome: "Combine melody and support.", status: "designed" },
  { id: "reading", title: "Reading Music", outcome: "Connect sound and touch to notation.", status: "designed" },
  { id: "expression", title: "Expression", outcome: "Shape dynamics, articulation, and pedal.", status: "designed" },
  { id: "piece", title: "First Complete Piece", outcome: "Integrate the foundations into music.", status: "designed" },
] as const;

export const PRACTICE_EXERCISES: PerformanceExercise[] = [
  {
    id: "practice-find-c",
    kind: "play-pitch-class",
    prompt: "Find a C without using the note labels.",
    hint: "C sits immediately left of each group of two black keys.",
    targetPitchClasses: [0],
    competency: { id: "piano.note-navigation.c", label: "C landmark navigation" },
    evaluationMode: "objective",
  },
  {
    id: "practice-c-major-up",
    kind: "play-scale",
    prompt: "Play C major upward: C D E F G A B C.",
    hint: "Use only the white keys, beginning and ending on C.",
    targetNotes: [60, 62, 64, 65, 67, 69, 71, 72],
    ordered: true,
    competency: { id: "piano.scale.c-major.ascending", label: "C major ascending", prerequisites: ["piano.note-navigation.c"] },
    evaluationMode: "objective",
  },
  {
    id: "practice-steady-pulse",
    kind: "rhythm",
    prompt: "Tap any one key four times with an even pulse.",
    hint: "Count 1, 2, 3, 4 at about two counts per second. The key itself does not matter.",
    targetIntervalsMs: [500, 500, 500],
    toleranceMs: 170,
    competency: { id: "piano.rhythm.steady-pulse", label: "Steady pulse" },
    evaluationMode: "objective",
  },
  {
    id: "practice-five-note-return",
    kind: "play-sequence",
    prompt: "Walk away from C and return: C D E F G F E D C.",
    hint: "Move one white key at a time. There is no speed target.",
    targetNotes: [60, 62, 64, 65, 67, 65, 64, 62, 60],
    ordered: true,
    competency: { id: "piano.control.five-note-return", label: "Five-note control", prerequisites: ["piano.note-navigation.c"] },
    evaluationMode: "objective",
  },
  {
    id: "practice-hold-c",
    kind: "hold-notes",
    prompt: "Press middle C, let it sound for two seconds, then release.",
    hint: "Keep the key down while you count slowly: one… two… then release.",
    targetNotes: [60],
    minimumHoldMs: 1800,
    competency: { id: "piano.control.note-duration", label: "Controlled note duration", prerequisites: ["piano.note-navigation.c"] },
    evaluationMode: "objective",
  },
  {
    id: "practice-c-major-down",
    kind: "play-scale",
    prompt: "Play C major downward: C B A G F E D C.",
    hint: "Begin on the higher C and move left using only white keys.",
    targetNotes: [72, 71, 69, 67, 65, 64, 62, 60],
    ordered: true,
    competency: { id: "piano.scale.c-major.descending", label: "C major descending", prerequisites: ["piano.scale.c-major.ascending"] },
    evaluationMode: "objective",
  },
  {
    id: "practice-primary-chords",
    kind: "play-sequence",
    prompt: "Build the primary chords as broken shapes: C E G, F A C, G B D.",
    hint: "Play each chord from its root upward. The whole route is C E G F A C G B D.",
    targetNotes: [60, 64, 67, 65, 69, 72, 67, 71, 74],
    ordered: true,
    competency: { id: "piano.chord.primary-triads-c", label: "C, F, and G chord tones", prerequisites: ["piano.scale.c-major.ascending"] },
    evaluationMode: "objective",
  },
  {
    id: "practice-first-arpeggio",
    kind: "play-sequence",
    prompt: "Open C major across time: C E G C, then C G E C.",
    hint: "Ascending: C E G high C. Descending: high C G E low C.",
    targetNotes: [60, 64, 67, 72, 72, 67, 64, 60],
    ordered: true,
    competency: { id: "piano.arpeggio.c-major.one-octave", label: "First C major arpeggio", prerequisites: ["piano.chord.c-major.construction"] },
    evaluationMode: "objective",
  },
];
