import type { KnowledgeNode } from "@/content/knowledge/types";

/**
 * Seed Knowledge DNA graph for Ethical Hacking Phase 1 foundations.
 * Nodes with topicRef map into live curriculum; planned stubs cover gaps.
 */
export const KNOWLEDGE_NODES: KnowledgeNode[] = [
  {
    id: "computer-fundamentals",
    title: "Computer Fundamentals",
    description: "Desktop literacy, files, accounts, and safe basic troubleshooting.",
    domain: "foundations",
    difficulty: "foundation",
    status: "live",
    topicRef: { certId: "computer-fundamentals", topicId: "cf-what-is-a-computer" },
    prerequisites: [],
    recommendedPrerequisites: [],
    relatedConcepts: ["windows-literacy"],
    redTeamConnections: [],
    blueTeamConnections: [],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "computer-fundamentals", confidence: "conceptual" },
      { certFamily: "a-plus", confidence: "conceptual", note: "CF prepares for A+" },
    ],
    labs: [],
  },
  {
    id: "windows-literacy",
    title: "Windows Literacy",
    description: "Settings, Task Manager, updates, and everyday Windows admin habits.",
    domain: "foundations",
    difficulty: "foundation",
    status: "live",
    topicRef: {
      certId: "computer-fundamentals",
      topicId: "cf-task-manager-restart-backup",
    },
    prerequisites: ["computer-fundamentals"],
    recommendedPrerequisites: [],
    relatedConcepts: ["powershell-basics"],
    redTeamConnections: [],
    blueTeamConnections: [],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "computer-fundamentals", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "networking-fundamentals",
    title: "Networking Fundamentals",
    description: "OSI/TCP-IP mental models and how packets move between hosts.",
    domain: "networking",
    difficulty: "foundation",
    status: "live",
    topicRef: { certId: "ccna", topicId: "osi-model" },
    prerequisites: [],
    recommendedPrerequisites: ["computer-fundamentals"],
    relatedConcepts: ["tcp-ip", "ports-protocols"],
    redTeamConnections: [],
    blueTeamConnections: [],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "ccna", examVersion: "200-301", confidence: "conceptual" },
      { certFamily: "network-plus", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "tcp-ip",
    title: "TCP/IP",
    description: "Addressing, encapsulation, and the four-layer TCP/IP model.",
    domain: "networking",
    difficulty: "beginner",
    status: "live",
    topicRef: { certId: "ccna", topicId: "tcp-ip-model" },
    prerequisites: ["networking-fundamentals"],
    recommendedPrerequisites: [],
    relatedConcepts: ["ports-protocols", "dns", "dhcp"],
    redTeamConnections: [],
    blueTeamConnections: [],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "ccna", confidence: "conceptual" },
      { certFamily: "network-plus", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "ports-protocols",
    title: "Ports and Protocols",
    description: "Common services and the ports they use on the wire.",
    domain: "networking",
    difficulty: "beginner",
    status: "live",
    topicRef: { certId: "network-plus", topicId: "network-tools" },
    prerequisites: ["tcp-ip"],
    recommendedPrerequisites: [],
    relatedConcepts: ["dns", "http-https"],
    redTeamConnections: ["recon-concepts"],
    blueTeamConnections: ["logging-monitoring"],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "network-plus", confidence: "conceptual" },
      { certFamily: "ccna", confidence: "conceptual" },
      { certFamily: "a-plus", examVersion: "220-1201", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "dns",
    title: "DNS",
    description: "Name resolution, record types, and why broken DNS looks like “the internet is down.”",
    domain: "networking",
    difficulty: "beginner",
    status: "live",
    topicRef: { certId: "ccna", topicId: "dns" },
    prerequisites: ["tcp-ip"],
    recommendedPrerequisites: ["ports-protocols"],
    relatedConcepts: ["http-https"],
    redTeamConnections: ["recon-concepts"],
    blueTeamConnections: ["logging-monitoring"],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "ccna", confidence: "conceptual" },
      { certFamily: "network-plus", confidence: "conceptual" },
      { certFamily: "a-plus", examVersion: "220-1201", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "dhcp",
    title: "DHCP",
    description: "Automatic addressing and what happens when leases or scopes fail.",
    domain: "networking",
    difficulty: "beginner",
    status: "live",
    topicRef: { certId: "ccna", topicId: "dhcp" },
    prerequisites: ["tcp-ip"],
    recommendedPrerequisites: [],
    relatedConcepts: ["dns"],
    redTeamConnections: [],
    blueTeamConnections: [],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "ccna", confidence: "conceptual" },
      { certFamily: "network-plus", confidence: "conceptual" },
      { certFamily: "a-plus", examVersion: "220-1201", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "subnetting",
    title: "Subnetting",
    description: "Prefix lengths, networks, and host capacity.",
    domain: "networking",
    difficulty: "intermediate",
    status: "live",
    topicRef: { certId: "ccna", topicId: "subnetting" },
    prerequisites: ["tcp-ip"],
    recommendedPrerequisites: [],
    relatedConcepts: ["routing-switching"],
    redTeamConnections: [],
    blueTeamConnections: [],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "ccna", confidence: "conceptual" },
      { certFamily: "network-plus", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "routing-switching",
    title: "Routing and Switching",
    description: "How frames and packets are forwarded inside and between networks.",
    domain: "networking",
    difficulty: "intermediate",
    status: "live",
    topicRef: { certId: "ccna", topicId: "routing-fundamentals" },
    prerequisites: ["tcp-ip", "subnetting"],
    recommendedPrerequisites: [],
    relatedConcepts: [],
    redTeamConnections: ["lateral-movement-concepts"],
    blueTeamConnections: ["network-segmentation-basics"],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "ccna", confidence: "conceptual" },
      { certFamily: "network-plus", confidence: "conceptual" },
      { certFamily: "a-plus", examVersion: "220-1201", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "http-https",
    title: "HTTP and HTTPS",
    description: "Request/response web traffic and TLS at a conceptual level.",
    domain: "web",
    difficulty: "beginner",
    status: "partial",
    topicRef: {
      certId: "computer-fundamentals",
      topicId: "cf-browser-url-cloud",
    },
    prerequisites: ["tcp-ip"],
    recommendedPrerequisites: ["dns", "ports-protocols"],
    relatedConcepts: ["browser-sessions", "apis"],
    redTeamConnections: ["web-injection-concepts"],
    blueTeamConnections: ["logging-monitoring"],
    remediationConnections: ["secure-headers-concepts"],
    certificationMappings: [
      { certFamily: "network-plus", confidence: "conceptual" },
      { certFamily: "ejpt", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "browser-sessions",
    title: "Cookies and Sessions",
    description: "How browsers keep users signed in — planned deep track.",
    domain: "web",
    difficulty: "beginner",
    status: "planned",
    prerequisites: ["http-https"],
    recommendedPrerequisites: [],
    relatedConcepts: ["authentication"],
    redTeamConnections: ["web-injection-concepts"],
    blueTeamConnections: ["secure-headers-concepts"],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "ejpt", confidence: "conceptual" },
      { certFamily: "security-plus", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "apis",
    title: "APIs",
    description: "REST-style request patterns — planned Type B track.",
    domain: "web",
    difficulty: "beginner",
    status: "planned",
    prerequisites: ["http-https"],
    recommendedPrerequisites: ["authentication"],
    relatedConcepts: ["sql-fundamentals"],
    redTeamConnections: [],
    blueTeamConnections: [],
    remediationConnections: [],
    certificationMappings: [{ certFamily: "other", confidence: "conceptual", note: "REST planned track" }],
    labs: [],
  },
  {
    id: "linux-fundamentals",
    title: "Linux Fundamentals",
    description: "Filesystem layout, shell basics, and Linux mental models.",
    domain: "systems",
    difficulty: "beginner",
    status: "live",
    topicRef: { certId: "linux-plus", topicId: "linux-filesystem" },
    prerequisites: ["computer-fundamentals"],
    recommendedPrerequisites: [],
    relatedConcepts: ["linux-permissions", "processes-services", "bash-basics"],
    redTeamConnections: ["privilege-escalation-concepts"],
    blueTeamConnections: ["logging-monitoring"],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "linux-plus", confidence: "conceptual" },
      { certFamily: "ejpt", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "linux-permissions",
    title: "Users, Groups, and Permissions",
    description: "Least privilege on Linux files and directories.",
    domain: "systems",
    difficulty: "beginner",
    status: "live",
    topicRef: { certId: "linux-plus", topicId: "permissions" },
    prerequisites: ["linux-fundamentals"],
    recommendedPrerequisites: [],
    relatedConcepts: ["processes-services"],
    redTeamConnections: ["privilege-escalation-concepts"],
    blueTeamConnections: [],
    remediationConnections: ["hardening-basics"],
    certificationMappings: [
      { certFamily: "linux-plus", confidence: "conceptual" },
      { certFamily: "security-plus", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "processes-services",
    title: "Processes and Services",
    description: "What is running, what starts at boot, and how to inspect it safely.",
    domain: "systems",
    difficulty: "beginner",
    status: "live",
    topicRef: { certId: "linux-plus", topicId: "processes" },
    prerequisites: ["linux-fundamentals"],
    recommendedPrerequisites: ["powershell-basics"],
    relatedConcepts: [],
    redTeamConnections: ["persistence-concepts"],
    blueTeamConnections: ["logging-monitoring"],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "linux-plus", confidence: "conceptual" },
      { certFamily: "cysa-plus", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "bash-basics",
    title: "Bash",
    description: "Shell language for Linux — planned Type B track (pairs with Linux+).",
    domain: "systems",
    difficulty: "beginner",
    status: "planned",
    prerequisites: ["linux-fundamentals"],
    recommendedPrerequisites: [],
    relatedConcepts: ["powershell-basics"],
    redTeamConnections: [],
    blueTeamConnections: [],
    remediationConnections: [],
    certificationMappings: [{ certFamily: "linux-plus", confidence: "conceptual" }],
    labs: [],
  },
  {
    id: "powershell-basics",
    title: "PowerShell",
    description: "Windows automation with cmdlets, pipelines, and safe first commands.",
    domain: "systems",
    difficulty: "beginner",
    status: "live",
    topicRef: { certId: "powershell", topicId: "ps-why-the-shell" },
    prerequisites: ["windows-literacy"],
    recommendedPrerequisites: [],
    relatedConcepts: ["processes-services"],
    redTeamConnections: [],
    blueTeamConnections: ["logging-monitoring"],
    remediationConnections: [],
    certificationMappings: [{ certFamily: "other", confidence: "conceptual", note: "PowerShell skill track" }],
    labs: [],
  },
  {
    id: "python-fundamentals",
    title: "Python Fundamentals",
    description: "Scripting basics — planned Type B track.",
    domain: "automation",
    difficulty: "beginner",
    status: "planned",
    prerequisites: ["computer-fundamentals"],
    recommendedPrerequisites: ["git-github"],
    relatedConcepts: [],
    redTeamConnections: [],
    blueTeamConnections: [],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "ejpt", confidence: "conceptual" },
      { certFamily: "other", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "git-github",
    title: "Git and GitHub",
    description: "Version control, remotes, and professional change workflow.",
    domain: "automation",
    difficulty: "beginner",
    status: "live",
    topicRef: { certId: "git-github", topicId: "git-why-version-control" },
    prerequisites: [],
    recommendedPrerequisites: ["computer-fundamentals"],
    relatedConcepts: ["python-fundamentals"],
    redTeamConnections: [],
    blueTeamConnections: [],
    remediationConnections: [],
    certificationMappings: [{ certFamily: "other", confidence: "conceptual" }],
    labs: [],
  },
  {
    id: "sql-fundamentals",
    title: "SQL and Relational Databases",
    description: "SELECT/JOIN mental models — planned Type B track.",
    domain: "data",
    difficulty: "beginner",
    status: "planned",
    prerequisites: ["computer-fundamentals"],
    recommendedPrerequisites: [],
    relatedConcepts: ["apis"],
    redTeamConnections: ["web-injection-concepts"],
    blueTeamConnections: [],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "ejpt", confidence: "conceptual" },
      { certFamily: "other", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "authentication",
    title: "Authentication",
    description: "Proving identity — passwords, MFA, and session handoff concepts.",
    domain: "security",
    difficulty: "beginner",
    status: "live",
    topicRef: { certId: "security-plus", topicId: "authentication" },
    prerequisites: ["computer-fundamentals"],
    recommendedPrerequisites: ["http-https", "browser-sessions"],
    relatedConcepts: ["authorization", "cryptography-fundamentals"],
    redTeamConnections: ["auth-weakness-concepts"],
    blueTeamConnections: ["auth-detection-concepts"],
    remediationConnections: ["hardening-basics"],
    certificationMappings: [
      { certFamily: "security-plus", confidence: "conceptual" },
      { certFamily: "ejpt", confidence: "conceptual" },
    ],
    labs: [
      {
        id: "lab-auth-misconfig-sandbox",
        title: "Auth misconfiguration sandbox (planned)",
        requiresPrerequisites: true,
      },
    ],
  },
  {
    id: "authorization",
    title: "Authorization",
    description: "What an identity is allowed to do after it authenticates.",
    domain: "security",
    difficulty: "beginner",
    status: "live",
    topicRef: { certId: "security-plus", topicId: "authorization" },
    prerequisites: ["authentication"],
    recommendedPrerequisites: [],
    relatedConcepts: ["linux-permissions"],
    redTeamConnections: ["privilege-escalation-concepts"],
    blueTeamConnections: [],
    remediationConnections: ["hardening-basics"],
    certificationMappings: [
      { certFamily: "security-plus", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "cryptography-fundamentals",
    title: "Cryptography Fundamentals",
    description: "Confidentiality, integrity, hashing, and TLS at exam literacy depth.",
    domain: "security",
    difficulty: "beginner",
    status: "live",
    topicRef: { certId: "security-plus", topicId: "cryptography-basics" },
    prerequisites: ["computer-fundamentals"],
    recommendedPrerequisites: ["http-https"],
    relatedConcepts: ["authentication"],
    redTeamConnections: [],
    blueTeamConnections: [],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "security-plus", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "logging-monitoring",
    title: "Logging and Monitoring",
    description: "What to collect and how analysts triage signals.",
    domain: "security-ops",
    difficulty: "intermediate",
    status: "live",
    topicRef: { certId: "cysa-plus", topicId: "log-analysis" },
    prerequisites: ["linux-fundamentals"],
    recommendedPrerequisites: ["ports-protocols"],
    relatedConcepts: ["siem-fundamentals"],
    redTeamConnections: [],
    blueTeamConnections: ["incident-response"],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "cysa-plus", confidence: "conceptual" },
      { certFamily: "linux-plus", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "siem-fundamentals",
    title: "SIEM Fundamentals",
    description: "Centralized alerts, correlation, and detection engineering basics.",
    domain: "security-ops",
    difficulty: "intermediate",
    status: "live",
    topicRef: { certId: "cysa-plus", topicId: "siem-basics" },
    prerequisites: ["logging-monitoring"],
    recommendedPrerequisites: [],
    relatedConcepts: ["incident-response"],
    redTeamConnections: [],
    blueTeamConnections: ["incident-response"],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "cysa-plus", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "vulnerability-management",
    title: "Vulnerability Management",
    description: "Find, prioritize, and track weaknesses without treating every CVE as equal.",
    domain: "security-ops",
    difficulty: "intermediate",
    status: "live",
    topicRef: { certId: "security-plus", topicId: "vulnerability-management" },
    prerequisites: ["networking-fundamentals"],
    recommendedPrerequisites: ["authentication"],
    relatedConcepts: ["incident-response"],
    redTeamConnections: ["exploitation-concepts"],
    blueTeamConnections: ["hardening-basics"],
    remediationConnections: ["hardening-basics"],
    certificationMappings: [
      { certFamily: "security-plus", confidence: "conceptual" },
      { certFamily: "cysa-plus", confidence: "conceptual" },
      { certFamily: "ejpt", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "incident-response",
    title: "Incident Response",
    description: "Contain, eradicate, recover, and document — blue-team workflow.",
    domain: "security-ops",
    difficulty: "intermediate",
    status: "live",
    topicRef: { certId: "security-plus", topicId: "incident-response" },
    prerequisites: ["logging-monitoring"],
    recommendedPrerequisites: ["siem-fundamentals"],
    relatedConcepts: ["vulnerability-management"],
    redTeamConnections: [],
    blueTeamConnections: [],
    remediationConnections: ["hardening-basics"],
    certificationMappings: [
      { certFamily: "security-plus", confidence: "conceptual" },
      { certFamily: "cysa-plus", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "cloud-fundamentals",
    title: "Cloud Fundamentals",
    description: "Shared responsibility and cloud building blocks.",
    domain: "cloud",
    difficulty: "beginner",
    status: "live",
    topicRef: { certId: "aws-cloud-practitioner", topicId: "cloud-concepts" },
    prerequisites: ["networking-fundamentals"],
    recommendedPrerequisites: [],
    relatedConcepts: [],
    redTeamConnections: [],
    blueTeamConnections: [],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "other", confidence: "conceptual", note: "AWS CP / Azure" },
      { certFamily: "a-plus", examVersion: "220-1201", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "active-directory-fundamentals",
    title: "Active Directory Fundamentals",
    description: "Directory services identity model — planned gap.",
    domain: "windows-enterprise",
    difficulty: "intermediate",
    status: "planned",
    prerequisites: ["windows-literacy", "authentication"],
    recommendedPrerequisites: ["powershell-basics"],
    relatedConcepts: ["authorization"],
    redTeamConnections: ["lateral-movement-concepts"],
    blueTeamConnections: ["logging-monitoring"],
    remediationConnections: ["hardening-basics"],
    certificationMappings: [
      { certFamily: "ejpt", confidence: "conceptual" },
      { certFamily: "pnpt", confidence: "conceptual" },
    ],
    labs: [],
  },
  // Conceptual EH nodes (no operational content)
  {
    id: "auth-weakness-concepts",
    title: "Authentication Weakness Categories",
    description:
      "Conceptual categories of weak authentication (lab-safe). No operational attack steps.",
    domain: "ethical-hacking",
    difficulty: "intermediate",
    status: "planned",
    prerequisites: ["authentication"],
    recommendedPrerequisites: ["browser-sessions"],
    relatedConcepts: ["auth-detection-concepts"],
    redTeamConnections: [],
    blueTeamConnections: ["auth-detection-concepts"],
    remediationConnections: ["hardening-basics"],
    certificationMappings: [
      { certFamily: "ejpt", confidence: "conceptual" },
      { certFamily: "security-plus", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "auth-detection-concepts",
    title: "Authentication Detection & Logging",
    description: "Which logs and alerts typically surface auth abuse in a lab SIEM.",
    domain: "ethical-hacking",
    difficulty: "intermediate",
    status: "planned",
    prerequisites: ["authentication", "logging-monitoring"],
    recommendedPrerequisites: ["siem-fundamentals"],
    relatedConcepts: ["auth-weakness-concepts"],
    redTeamConnections: [],
    blueTeamConnections: [],
    remediationConnections: ["hardening-basics"],
    certificationMappings: [
      { certFamily: "cysa-plus", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "web-injection-concepts",
    title: "Web Injection Concepts",
    description:
      "How untrusted input can affect HTML/SQL contexts — conceptual only; labs TBD in sandboxes.",
    domain: "ethical-hacking",
    difficulty: "intermediate",
    status: "planned",
    prerequisites: ["http-https"],
    recommendedPrerequisites: ["sql-fundamentals", "browser-sessions"],
    relatedConcepts: ["secure-headers-concepts"],
    redTeamConnections: [],
    blueTeamConnections: ["secure-headers-concepts"],
    remediationConnections: ["secure-headers-concepts"],
    certificationMappings: [
      { certFamily: "ejpt", confidence: "conceptual" },
      { certFamily: "oscp", confidence: "conceptual", note: "High-level only" },
    ],
    labs: [
      {
        id: "lab-reflected-xss-sandbox",
        title: "Reflected XSS (sandbox — planned)",
        requiresPrerequisites: true,
      },
      {
        id: "lab-stored-xss-sandbox",
        title: "Stored XSS (sandbox — planned)",
        requiresPrerequisites: true,
      },
      {
        id: "lab-dom-xss-sandbox",
        title: "DOM XSS (sandbox — planned)",
        requiresPrerequisites: true,
      },
    ],
  },
  {
    id: "secure-headers-concepts",
    title: "Output Encoding & CSP Concepts",
    description: "Defensive controls for injection classes — conceptual.",
    domain: "ethical-hacking",
    difficulty: "intermediate",
    status: "planned",
    prerequisites: ["http-https"],
    recommendedPrerequisites: ["web-injection-concepts"],
    relatedConcepts: [],
    redTeamConnections: [],
    blueTeamConnections: [],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "security-plus", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "recon-concepts",
    title: "Reconnaissance Concepts",
    description: "What information gathering means inside an authorized scope.",
    domain: "ethical-hacking",
    difficulty: "intermediate",
    status: "planned",
    prerequisites: ["networking-fundamentals", "ports-protocols"],
    recommendedPrerequisites: ["dns"],
    relatedConcepts: ["exploitation-concepts"],
    redTeamConnections: [],
    blueTeamConnections: ["logging-monitoring"],
    remediationConnections: [],
    certificationMappings: [{ certFamily: "ejpt", confidence: "conceptual" }],
    labs: [],
  },
  {
    id: "exploitation-concepts",
    title: "Exploitation Concepts",
    description:
      "Categories of taking advantage of a weakness in a sandbox — no real exploit payloads.",
    domain: "ethical-hacking",
    difficulty: "advanced",
    status: "planned",
    prerequisites: ["vulnerability-management", "recon-concepts"],
    recommendedPrerequisites: [],
    relatedConcepts: ["privilege-escalation-concepts"],
    redTeamConnections: [],
    blueTeamConnections: ["incident-response"],
    remediationConnections: ["hardening-basics"],
    certificationMappings: [
      { certFamily: "ejpt", confidence: "conceptual" },
      { certFamily: "pnpt", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "privilege-escalation-concepts",
    title: "Privilege Escalation Concepts",
    description: "Why least privilege matters; conceptual escalation categories in labs only.",
    domain: "ethical-hacking",
    difficulty: "advanced",
    status: "planned",
    prerequisites: ["linux-permissions", "authorization"],
    recommendedPrerequisites: ["processes-services"],
    relatedConcepts: ["lateral-movement-concepts"],
    redTeamConnections: [],
    blueTeamConnections: ["hardening-basics"],
    remediationConnections: ["hardening-basics"],
    certificationMappings: [
      { certFamily: "ejpt", confidence: "conceptual" },
      { certFamily: "oscp", confidence: "conceptual", note: "Conceptual only" },
    ],
    labs: [],
  },
  {
    id: "lateral-movement-concepts",
    title: "Lateral Movement Concepts",
    description: "Moving between hosts in a scoped lab network — conceptual.",
    domain: "ethical-hacking",
    difficulty: "advanced",
    status: "planned",
    prerequisites: ["routing-switching", "authentication"],
    recommendedPrerequisites: ["active-directory-fundamentals"],
    relatedConcepts: ["persistence-concepts"],
    redTeamConnections: [],
    blueTeamConnections: ["network-segmentation-basics"],
    remediationConnections: ["network-segmentation-basics"],
    certificationMappings: [
      { certFamily: "pnpt", confidence: "conceptual" },
      { certFamily: "cysa-plus", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "persistence-concepts",
    title: "Persistence Concepts (Simulated)",
    description:
      "How persistence is described in labs using harmless tokens — never real malware.",
    domain: "ethical-hacking",
    difficulty: "advanced",
    status: "planned",
    prerequisites: ["processes-services"],
    recommendedPrerequisites: [],
    relatedConcepts: [],
    redTeamConnections: [],
    blueTeamConnections: ["incident-response"],
    remediationConnections: ["hardening-basics"],
    certificationMappings: [{ certFamily: "cysa-plus", confidence: "conceptual" }],
    labs: [],
  },
  {
    id: "hardening-basics",
    title: "Hardening & Remediation Basics",
    description: "Patch, least privilege, and verify — defender close-out.",
    domain: "ethical-hacking",
    difficulty: "intermediate",
    status: "partial",
    topicRef: { certId: "security-plus", topicId: "secure-network-design" },
    prerequisites: ["vulnerability-management"],
    recommendedPrerequisites: ["incident-response"],
    relatedConcepts: [],
    redTeamConnections: [],
    blueTeamConnections: [],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "security-plus", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "network-segmentation-basics",
    title: "Network Segmentation Basics",
    description: "Limiting blast radius with zones and trust boundaries.",
    domain: "ethical-hacking",
    difficulty: "intermediate",
    status: "partial",
    topicRef: { certId: "security-plus", topicId: "secure-network-design" },
    prerequisites: ["routing-switching"],
    recommendedPrerequisites: [],
    relatedConcepts: ["hardening-basics"],
    redTeamConnections: [],
    blueTeamConnections: [],
    remediationConnections: [],
    certificationMappings: [
      { certFamily: "security-plus", confidence: "conceptual" },
      { certFamily: "network-plus", confidence: "conceptual" },
    ],
    labs: [],
  },
  {
    id: "cross-site-scripting",
    title: "Cross-Site Scripting",
    description:
      "Featured Knowledge DNA example — web injection class with red/blue follow-ups.",
    domain: "ethical-hacking",
    difficulty: "intermediate",
    status: "planned",
    prerequisites: ["http-https", "browser-sessions"],
    recommendedPrerequisites: ["secure-headers-concepts"],
    relatedConcepts: ["web-injection-concepts"],
    redTeamConnections: ["web-injection-concepts"],
    blueTeamConnections: ["secure-headers-concepts", "logging-monitoring"],
    remediationConnections: ["secure-headers-concepts"],
    certificationMappings: [
      { certFamily: "ejpt", confidence: "conceptual" },
      { certFamily: "security-plus", confidence: "conceptual" },
    ],
    labs: [
      {
        id: "lab-reflected-xss-sandbox",
        title: "Reflected XSS (sandbox — planned)",
        requiresPrerequisites: true,
      },
      {
        id: "lab-stored-xss-sandbox",
        title: "Stored XSS (sandbox — planned)",
        requiresPrerequisites: true,
      },
      {
        id: "lab-dom-xss-sandbox",
        title: "DOM XSS (sandbox — planned)",
        requiresPrerequisites: true,
      },
    ],
  },
];

export function getKnowledgeNodes(): KnowledgeNode[] {
  return KNOWLEDGE_NODES;
}
