import type { ChoiceDrillItem } from "@/components/simulators/SimulatorRegistry";

export const CABLE_TYPE_POOL: ChoiceDrillItem[] = [
  {
    id: "cable-1",
    prompt: "Which cable type and connector are standard for Ethernet UTP desktop connections?",
    choices: [
      { id: "a", text: "Cat 5e/6 UTP with RJ-45" },
      { id: "b", text: "Coax with F-type" },
      { id: "c", text: "Multimode fiber with SC only" },
      { id: "d", text: "Twinax with LC" },
    ],
    correctChoiceId: "a",
    weakConcept: "UTP / RJ-45",
    explanation: "Copper Ethernet to PCs and switches uses twisted pair terminated with 8P8C (RJ-45).",
  },
  {
    id: "cable-2",
    prompt: "Maximum recommended length for a single Cat 6 Ethernet run (horizontal)?",
    choices: [
      { id: "a", text: "100 meters (328 feet)" },
      { id: "b", text: "500 meters" },
      { id: "c", text: "10 meters" },
      { id: "d", text: "1 kilometer" },
    ],
    correctChoiceId: "a",
    weakConcept: "Ethernet cable length limit",
    explanation: "TIA/EIA specifies 100 m for structured copper cabling channel.",
  },
  {
    id: "cable-3",
    prompt: "Straight-through vs crossover copper cable:",
    choices: [
      { id: "a", text: "Straight-through: host/switch; crossover (legacy): like devices" },
      { id: "b", text: "Crossover always used PC to switch today" },
      { id: "c", text: "Straight-through swaps all eight wires" },
      { id: "d", text: "Only fiber uses straight-through" },
    ],
    correctChoiceId: "a",
    weakConcept: "Straight vs crossover",
    explanation: "Auto-MDIX makes crossover rare, but straight-through is still PC/switch standard.",
  },
  {
    id: "cable-4",
    prompt: "Single-mode fiber (SMF) vs multimode fiber (MMF):",
    choices: [
      { id: "a", text: "SMF: long distance, single light path; MMF: shorter, larger core" },
      { id: "b", text: "MMF only used for WAN over 80 km" },
      { id: "c", text: "SMF uses LED only" },
      { id: "d", text: "MMF has smaller core than SMF" },
    ],
    correctChoiceId: "a",
    weakConcept: "SMF vs MMF",
    explanation: "SMF uses laser for long haul; MMF (OM3/OM4) for data center / campus short runs.",
  },
  {
    id: "cable-5",
    prompt: "Which connector is common on Cisco SFP+ 10G fiber modules?",
    choices: [
      { id: "a", text: "LC duplex" },
      { id: "b", text: "RJ-45" },
      { id: "c", text: "BNC" },
      { id: "d", text: "DB-9 serial" },
    ],
    correctChoiceId: "a",
    weakConcept: "Fiber connectors (LC)",
    explanation: "SFP/SFP+ modules typically use LC; older GBIC might use SC.",
  },
  {
    id: "cable-6",
    prompt: "Cat 6 vs Cat 5e for Gigabit Ethernet:",
    choices: [
      { id: "a", text: "Both support 1 Gbps to 100 m; Cat 6 has stricter specs and headroom for 10G short runs" },
      { id: "b", text: "Cat 5e cannot run Gigabit" },
      { id: "c", text: "Cat 6 is coax-only" },
      { id: "d", text: "Cat 5e is fiber" },
    ],
    correctChoiceId: "a",
    weakConcept: "Cable category ratings",
    explanation: "Cat 5e is rated for 1 Gbps; Cat 6 improves crosstalk performance.",
  },
  {
    id: "cable-7",
    prompt: "A console cable for Cisco router initial setup is typically:",
    choices: [
      { id: "a", text: "Rollover (RJ-45 to DB-9/USB adapter) for serial console" },
      { id: "b", text: "Straight-through Cat 6 for WAN" },
      { id: "c", text: "Coax RG-6" },
      { id: "d", text: "Twinax for stacking" },
    ],
    correctChoiceId: "a",
    weakConcept: "Console cabling",
    explanation: "Console port uses RJ-45 rollover to USB/serial adapter for out-of-band management.",
  },
  {
    id: "cable-8",
    prompt: "Plenum-rated cable jacket is required when:",
    choices: [
      { id: "a", text: "Cable runs through air-handling spaces (lower smoke/toxicity)" },
      { id: "b", text: "Only outdoor burial" },
      { id: "c", text: "Connecting two PCs directly" },
      { id: "d", text: "Using PoE only" },
    ],
    correctChoiceId: "a",
    weakConcept: "Plenum vs riser cable",
    explanation: "Plenum (CMP) jackets meet fire code in ceiling/air duct runs.",
  },
  {
    id: "cable-9",
    prompt: "PoE (Power over Ethernet) delivers power on:",
    choices: [
      { id: "a", text: "Unused pairs or data pairs (802.3af/at/bt standards)" },
      { id: "b", text: "Fiber optic core" },
      { id: "c", text: "Separate 110V AC only" },
      { id: "d", text: "Coax center conductor exclusively" },
    ],
    correctChoiceId: "a",
    weakConcept: "PoE basics",
    explanation: "802.3af/at/bt supply DC power over the same UTP as data to phones/APs/cameras.",
  },
  {
    id: "cable-10",
    prompt: "T568A vs T568B wiring standards differ in:",
    choices: [
      { id: "a", text: "Pin/pair color order; both work if same on both ends" },
      { id: "b", text: "Maximum speed (T568B is 10G only)" },
      { id: "c", text: "One is fiber, one is copper" },
      { id: "d", text: "T568A is crossover only" },
    ],
    correctChoiceId: "a",
    weakConcept: "T568A vs T568B",
    explanation: "Use one standard consistently; T568B is common in US commercial installs.",
  },
];
