import type { ChoiceDrillItem } from "@/components/simulators/SimulatorRegistry";

export const DNS_RECORD_POOL: ChoiceDrillItem[] = [
  {
    id: "dns-1",
    prompt: "Which record maps a hostname to an IPv4 address?",
    choices: [
      { id: "a", text: "A" },
      { id: "b", text: "AAAA" },
      { id: "c", text: "MX" },
      { id: "d", text: "NS" },
    ],
    correctChoiceId: "a",
    weakConcept: "DNS A record",
    explanation: "A records point names to 32-bit IPv4 addresses.",
  },
  {
    id: "dns-2",
    prompt: "Which record maps a hostname to an IPv6 address?",
    choices: [
      { id: "a", text: "AAAA" },
      { id: "b", text: "A" },
      { id: "c", text: "PTR" },
      { id: "d", text: "CAA" },
    ],
    correctChoiceId: "a",
    weakConcept: "DNS AAAA record",
    explanation: "AAAA (quad-A) records hold 128-bit IPv6 addresses.",
  },
  {
    id: "dns-3",
    prompt: "An MX record specifies:",
    choices: [
      { id: "a", text: "Mail exchange server for the domain" },
      { id: "b", text: "Primary DNS server only" },
      { id: "c", text: "HTTPS certificate authority" },
      { id: "d", text: "Reverse lookup for IPv4" },
    ],
    correctChoiceId: "a",
    weakConcept: "DNS MX record",
    explanation: "MX records list mail servers with preference values for delivery order.",
  },
  {
    id: "dns-4",
    prompt: "A CNAME record:",
    choices: [
      { id: "a", text: "Aliases one name to another canonical name" },
      { id: "b", text: "Stores IPv4 addresses only" },
      { id: "c", text: "Replaces NS records" },
      { id: "d", text: "Defines SPF for email" },
    ],
    correctChoiceId: "a",
    weakConcept: "DNS CNAME record",
    explanation: "CNAME creates an alias; the target must be a hostname, not raw IP.",
  },
  {
    id: "dns-5",
    prompt: "Which record type is used for reverse DNS (IP → name)?",
    choices: [
      { id: "a", text: "PTR" },
      { id: "b", text: "A" },
      { id: "c", text: "SOA" },
      { id: "d", text: "TXT" },
    ],
    correctChoiceId: "a",
    weakConcept: "Reverse DNS (PTR)",
    explanation: "PTR records live in in-addr.arpa (IPv4) or ip6.arpa (IPv6) zones.",
  },
  {
    id: "dns-6",
    prompt: "NS records identify:",
    choices: [
      { id: "a", text: "Authoritative name servers for a zone" },
      { id: "b", text: "Web server IP addresses" },
      { id: "c", text: "Mail routing only" },
      { id: "d", text: "DHCP scopes" },
    ],
    correctChoiceId: "a",
    weakConcept: "DNS NS record",
    explanation: "NS records delegate a zone to one or more authoritative servers.",
  },
  {
    id: "dns-7",
    prompt: "SOA (Start of Authority) record contains:",
    choices: [
      { id: "a", text: "Primary NS, admin email, serial, refresh/retry/expire timers" },
      { id: "b", text: "Only the A record for www" },
      { id: "c", text: "TLS certificate pins" },
      { id: "d", text: "MAC address of the DNS server" },
    ],
    correctChoiceId: "a",
    weakConcept: "DNS SOA record",
    explanation: "SOA defines zone metadata and timing for secondary server synchronization.",
  },
  {
    id: "dns-8",
    prompt: "A client queries its resolver for www.example.com. The resolver first checks:",
    choices: [
      { id: "a", text: "Local cache / previously cached records" },
      { id: "b", text: "Root NS only, always" },
      { id: "c", text: "DHCP server" },
      { id: "d", text: "SMTP MX only" },
    ],
    correctChoiceId: "a",
    weakConcept: "DNS resolution order",
    explanation: "Resolvers cache answers; cache miss triggers recursive lookup from root downward.",
  },
  {
    id: "dns-9",
    prompt: "TXT records are commonly used for:",
    choices: [
      { id: "a", text: "SPF, DKIM, domain verification strings" },
      { id: "b", text: "IPv6 only address mapping" },
      { id: "c", text: "Replacing A records" },
      { id: "d", text: "STP bridge priority" },
    ],
    correctChoiceId: "a",
    weakConcept: "DNS TXT record use",
    explanation: "TXT holds arbitrary text — widely used for email auth and verification.",
  },
  {
    id: "dns-10",
    prompt: "Which port and transport does standard DNS use?",
    choices: [
      { id: "a", text: "UDP/TCP 53" },
      { id: "b", text: "UDP 67" },
      { id: "c", text: "TCP 443 only" },
      { id: "d", text: "UDP 123" },
    ],
    correctChoiceId: "a",
    weakConcept: "DNS transport",
    explanation: "DNS primarily uses UDP 53; TCP 53 is used for large responses and zone transfers.",
  },
];
