import type { ChoiceDrillItem } from "@/components/simulators/SimulatorRegistry";

export const IP_RANGE_POOL: ChoiceDrillItem[] = [
  {
    id: "ipr-1",
    prompt: "10.50.1.200 is best classified as:",
    choices: [
      { id: "a", text: "Private (RFC 1918)" },
      { id: "b", text: "Public routable" },
      { id: "c", text: "Loopback" },
      { id: "d", text: "Multicast" },
    ],
    correctChoiceId: "a",
    weakConcept: "RFC 1918 private — 10.x",
    explanation: "Any 10.x.x.x address is private (10.0.0.0/8). NAT translates it for Internet access.",
  },
  {
    id: "ipr-2",
    prompt: "172.20.15.4 is:",
    choices: [
      { id: "a", text: "Private (RFC 1918)" },
      { id: "b", text: "Public routable" },
      { id: "c", text: "APIPA / link-local" },
      { id: "d", text: "TEST-NET documentation" },
    ],
    correctChoiceId: "a",
    weakConcept: "172.16–172.31 private rule",
    explanation: "172.20.x.x falls inside 172.16.0.0/12 — only 172.16 through 172.31 are private.",
  },
  {
    id: "ipr-3",
    prompt: "172.40.1.1 is:",
    choices: [
      { id: "a", text: "Private because it starts with 172" },
      { id: "b", text: "Public routable" },
      { id: "c", text: "Loopback" },
      { id: "d", text: "Multicast" },
    ],
    correctChoiceId: "b",
    weakConcept: "172.40 trap — not all 172.x is private",
    explanation: "Only 172.16–172.31 are private. 172.40.1.1 is a public address — a common exam trap.",
  },
  {
    id: "ipr-4",
    prompt: "A host shows 169.254.88.22 with no DHCP server on the LAN. This is:",
    choices: [
      { id: "a", text: "APIPA / link-local (DHCP failed)" },
      { id: "b", text: "Private RFC 1918" },
      { id: "c", text: "Loopback" },
      { id: "d", text: "Multicast" },
    ],
    correctChoiceId: "a",
    weakConcept: "APIPA 169.254.0.0/16",
    explanation: "169.254.x.x is assigned automatically when DHCP is unavailable (APIPA).",
  },
  {
    id: "ipr-5",
    prompt: "224.0.0.5 (OSPF All SPF Routers) belongs to which category?",
    choices: [
      { id: "a", text: "IPv4 multicast (224.0.0.0/4)" },
      { id: "b", text: "Private address" },
      { id: "c", text: "Loopback" },
      { id: "d", text: "TEST-NET documentation" },
    ],
    correctChoiceId: "a",
    weakConcept: "Multicast range",
    explanation: "224.0.0.0/4 (224.0.0.0–239.255.255.255) is IPv4 multicast — one-to-many delivery.",
  },
  {
    id: "ipr-6",
    prompt: "192.0.2.42 appears in a vendor configuration guide example. It is:",
    choices: [
      { id: "a", text: "TEST-NET documentation only — not for production" },
      { id: "b", text: "A standard private LAN address like 192.168.x" },
      { id: "c", text: "APIPA" },
      { id: "d", text: "Public routable" },
    ],
    correctChoiceId: "a",
    weakConcept: "TEST-NET blocks",
    explanation: "192.0.2.0/24 is TEST-NET-1 for documentation. Do not use in live configs — unlike 192.168.x private space.",
  },
  {
    id: "ipr-7",
    prompt: "127.0.0.1 is used to:",
    choices: [
      { id: "a", text: "Test the local TCP/IP stack on this device" },
      { id: "b", text: "Reach the default gateway" },
      { id: "c", text: "Join an OSPF multicast group" },
      { id: "d", text: "Assign when DHCP fails" },
    ],
    correctChoiceId: "a",
    weakConcept: "Loopback 127.0.0.0/8",
    explanation: "127.0.0.0/8 is loopback — traffic never leaves the host. ping 127.0.0.1 tests the local stack.",
  },
  {
    id: "ipr-8",
    prompt: "Which three blocks are defined as private (RFC 1918)?",
    choices: [
      { id: "a", text: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16" },
      { id: "b", text: "127.0.0.0/8, 169.254.0.0/16, 224.0.0.0/4" },
      { id: "c", text: "192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24" },
      { id: "d", text: "10.0.0.0/8, 192.0.2.0/24, 172.40.0.0/16" },
    ],
    correctChoiceId: "a",
    weakConcept: "RFC 1918 trio",
    explanation: "Mnemonic: 10 = ALL · 172 = ONLY 16–31 · 192 = ONLY 168.",
  },
  {
    id: "ipr-9",
    prompt: "Private addresses reach the public Internet through:",
    choices: [
      { id: "a", text: "NAT at the edge router — not the switch" },
      { id: "b", text: "Direct routing without translation" },
      { id: "c", text: "Multicast registration" },
      { id: "d", text: "Loopback forwarding" },
    ],
    correctChoiceId: "a",
    weakConcept: "NAT and private addressing",
    explanation: "Private ranges are not globally routable. The router performs NAT to translate to a public address.",
  },
  {
    id: "ipr-10",
    prompt: "203.0.113.50 in a textbook diagram is most likely:",
    choices: [
      { id: "a", text: "TEST-NET-3 documentation address" },
      { id: "b", text: "A home router private address" },
      { id: "c", text: "APIPA" },
      { id: "d", text: "Loopback" },
    ],
    correctChoiceId: "a",
    weakConcept: "TEST-NET trio",
    explanation: "TEST-NET blocks: 192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24 — examples in docs only.",
  },
  {
    id: "ipr-11",
    prompt: "8.8.8.8 is:",
    choices: [
      { id: "a", text: "Public routable on the Internet" },
      { id: "b", text: "Private RFC 1918" },
      { id: "c", text: "Link-local APIPA" },
      { id: "d", text: "Reserved loopback" },
    ],
    correctChoiceId: "a",
    weakConcept: "Public vs private contrast",
    explanation: "8.8.8.8 is a globally routable public address (Google DNS). Compare to 10.x, 172.16–31.x, or 192.168.x.",
  },
  {
    id: "ipr-12",
    prompt: "Which range is IPv4 multicast?",
    choices: [
      { id: "a", text: "224.0.0.0/4" },
      { id: "b", text: "127.0.0.0/8" },
      { id: "c", text: "169.254.0.0/16" },
      { id: "d", text: "192.168.0.0/16" },
    ],
    correctChoiceId: "a",
    weakConcept: "Multicast block",
    explanation: "224.0.0.0/4 is multicast. 127 = loopback · 169.254 = APIPA · 192.168 = private.",
  },
];
