import type { ChoiceDrillItem } from "@/components/simulators/SimulatorRegistry";

export const IPV6_COMPRESS_POOL: ChoiceDrillItem[] = [
  {
    id: "ipv6-1",
    prompt: "What is the shortest valid compressed form of 2001:0db8:0000:0000:0000:0000:0000:0001?",
    choices: [
      { id: "a", text: "2001:db8::1" },
      { id: "b", text: "2001:db8:0:0:0:0:0:1" },
      { id: "c", text: "2001:db8::0:1" },
      { id: "d", text: "2001::db8:1" },
    ],
    correctChoiceId: "a",
    weakConcept: "IPv6 zero compression (::)",
    explanation: "Replace the longest run of zero hextets once with :: — here 2001:db8::1.",
  },
  {
    id: "ipv6-2",
    prompt: "Compress fe80:0000:0000:0000:0211:24ff:fe80:c12c:",
    choices: [
      { id: "a", text: "fe80::211:24ff:fe80:c12c" },
      { id: "b", text: "fe80::0211:24ff:fe80:c12c" },
      { id: "c", text: "fe80:0:0:0:211:24ff:fe80:c12c" },
      { id: "d", text: "fe80::" },
    ],
    correctChoiceId: "a",
    weakConcept: "Link-local compression",
    explanation: "Leading zeros in each hextet may be dropped; middle zero run becomes ::.",
  },
  {
    id: "ipv6-3",
    prompt: "Which address is the IPv6 loopback?",
    choices: [
      { id: "a", text: "::1" },
      { id: "b", text: "127.0.0.1" },
      { id: "c", text: "0:0:0:0:0:0:0:0" },
      { id: "d", text: "ff02::1" },
    ],
    correctChoiceId: "a",
    weakConcept: "IPv6 loopback",
    explanation: "::1 is localhost; equivalent to 127.0.0.1 in IPv4.",
  },
  {
    id: "ipv6-4",
    prompt: "Global unicast IPv6 addresses begin in which range?",
    choices: [
      { id: "a", text: "2000::/3" },
      { id: "b", text: "fe80::/10" },
      { id: "c", text: "fc00::/7" },
      { id: "d", text: "ff00::/8" },
    ],
    correctChoiceId: "a",
    weakConcept: "Global unicast prefix",
    explanation: "2000::/3 is the global unicast range — taught in the IPv6 address types lesson.",
  },
  {
    id: "ipv6-5",
    prompt: "fe80::/10 addresses are:",
    choices: [
      { id: "a", text: "Link-local (single layer-2 segment)" },
      { id: "b", text: "Globally routable" },
      { id: "c", text: "Multicast only" },
      { id: "d", text: "Deprecated" },
    ],
    correctChoiceId: "a",
    weakConcept: "Link-local scope",
    explanation: "fe80::/10 never leaves the local link; used for NDP and local services.",
  },
  {
    id: "ipv6-6",
    prompt: "Expand ::1 fully:",
    choices: [
      { id: "a", text: "0000:0000:0000:0000:0000:0000:0000:0001" },
      { id: "b", text: "0000:0000:0000:0001" },
      { id: "c", text: "0:0:0:1" },
      { id: "d", text: "0001::" },
    ],
    correctChoiceId: "a",
    weakConcept: "IPv6 expansion",
    explanation: "::1 expands to eight hextets with only the last hextet as 0001.",
  },
  {
    id: "ipv6-7",
    prompt: "2001:db8:85a3:0000:0000:8a2e:0370:7334 compressed:",
    choices: [
      { id: "a", text: "2001:db8:85a3::8a2e:370:7334" },
      { id: "b", text: "2001:db8:85a3::8a2e:0370:7334" },
      { id: "c", text: "2001:db8::85a3:8a2e:370:7334" },
      { id: "d", text: "2001:db8:85a3:0:0:8a2e:370:7334" },
    ],
    correctChoiceId: "a",
    weakConcept: "Mid-address zero compression",
    explanation: "Longest zero run (0000:0000) becomes ::; leading zeros in hextets dropped.",
  },
  {
    id: "ipv6-8",
    prompt: "How many hextets in a full IPv6 address?",
    choices: [
      { id: "a", text: "8" },
      { id: "b", text: "4" },
      { id: "c", text: "16" },
      { id: "d", text: "6" },
    ],
    correctChoiceId: "a",
    weakConcept: "IPv6 address structure",
    explanation: "128 bits = 8 groups of 16 bits (hextets), separated by colons.",
  },
  {
    id: "ipv6-9",
    prompt: "IPv6 multicast addresses begin with which prefix?",
    choices: [
      { id: "a", text: "ff00::/8" },
      { id: "b", text: "fe80::/10" },
      { id: "c", text: "2000::/3" },
      { id: "d", text: "fc00::/7" },
    ],
    correctChoiceId: "a",
    weakConcept: "IPv6 multicast prefix",
    explanation: "All IPv6 multicast addresses start with ff — IPv6 has no broadcast.",
  },
  {
    id: "ipv6-10",
    prompt: "Rule for using :: zero compression:",
    choices: [
      { id: "a", text: "Only once per address; longest sequence of zero hextets" },
      { id: "b", text: "As many times as needed" },
      { id: "c", text: "Only at the start" },
      { id: "d", text: "Never with link-local addresses" },
    ],
    correctChoiceId: "a",
    weakConcept: ":: compression rules",
    explanation: "RFC 5952: use :: once; prefer compressing the longest zero run.",
  },
];
