import type { ChoiceDrillItem } from "@/components/simulators/SimulatorRegistry";

export const NAT_TYPE_POOL: ChoiceDrillItem[] = [
  {
    id: "nat-1",
    prompt: "A home router maps many internal hosts to one public IP using different source ports. This is:",
    choices: [
      { id: "a", text: "PAT (NAT overload / NAPT)" },
      { id: "b", text: "Static NAT" },
      { id: "c", text: "Dynamic NAT without overload" },
      { id: "d", text: "Destination NAT only" },
    ],
    correctChoiceId: "a",
    weakConcept: "PAT / NAT overload",
    explanation: "PAT translates many private addresses to one public IP using unique port numbers.",
  },
  {
    id: "nat-2",
    prompt: "Static NAT maps:",
    choices: [
      { id: "a", text: "One private IP to one public IP (1:1, fixed)" },
      { id: "b", text: "Many private IPs to one public IP using ports" },
      { id: "c", text: "Public destination to private server only at Layer 2" },
      { id: "d", text: "MAC addresses to IP addresses" },
    ],
    correctChoiceId: "a",
    weakConcept: "Static NAT",
    explanation: "Static NAT is a permanent one-to-one mapping, often used for servers.",
  },
  {
    id: "nat-3",
    prompt: "Dynamic NAT without overload:",
    choices: [
      { id: "a", text: "Maps private IPs to a pool of public IPs (first-come, first-served)" },
      { id: "b", text: "Always uses port 443 for all sessions" },
      { id: "c", text: "Requires DNS ALG on every packet" },
      { id: "d", text: "Is identical to PAT" },
    ],
    correctChoiceId: "a",
    weakConcept: "Dynamic NAT pool",
    explanation: "Dynamic NAT assigns addresses from a pool; once the pool is exhausted, new sessions fail unless PAT is enabled.",
  },
  {
    id: "nat-4",
    prompt: "Port forwarding on a SOHO router is an example of:",
    choices: [
      { id: "a", text: "Static destination NAT (DNAT)" },
      { id: "b", text: "Source NAT only" },
      { id: "c", text: "NAT64" },
      { id: "d", text: "Reverse ARP" },
    ],
    correctChoiceId: "a",
    weakConcept: "Destination NAT / port forwarding",
    explanation: "Inbound traffic to a public IP:port is forwarded to an internal host — destination translation.",
  },
  {
    id: "nat-5",
    prompt: "Which address ranges are defined as private (RFC 1918)?",
    choices: [
      { id: "a", text: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16" },
      { id: "b", text: "169.254.0.0/16 only" },
      { id: "c", text: "224.0.0.0/4" },
      { id: "d", text: "127.0.0.0/8" },
    ],
    correctChoiceId: "a",
    weakConcept: "RFC 1918 private addressing",
    explanation: "These three ranges are not routable on the public Internet and require NAT for outbound access.",
  },
  {
    id: "nat-6",
    prompt: "Inside local vs inside global in Cisco NAT terminology:",
    choices: [
      { id: "a", text: "Local = address as seen on the inside network; global = address as seen on the outside" },
      { id: "b", text: "Local always means public; global always means private" },
      { id: "c", text: "Both refer to MAC addresses" },
      { id: "d", text: "Local is IPv6 only" },
    ],
    correctChoiceId: "a",
    weakConcept: "NAT terminology (local/global)",
    explanation: "Inside local is the actual private address; inside global is the translated public address seen externally.",
  },
  {
    id: "nat-7",
    prompt: "NAT typically breaks which protocol unless an ALG is used?",
    choices: [
      { id: "a", text: "FTP (embedded IP addresses in control channel)" },
      { id: "b", text: "ICMP echo only" },
      { id: "c", text: "DNS over UDP port 53 always" },
      { id: "d", text: "HTTPS on port 443" },
    ],
    correctChoiceId: "a",
    weakConcept: "NAT and application-layer gateways",
    explanation: "FTP embeds IP/port in the control connection; NAT ALGs rewrite those fields.",
  },
  {
    id: "nat-8",
    prompt: "Which Cisco command enables PAT (overload) on an interface?",
    choices: [
      { id: "a", text: "ip nat inside source list 1 interface Gig0/0 overload" },
      { id: "b", text: "ip nat outside source static" },
      { id: "c", text: "nat enable overload global" },
      { id: "d", text: "ip pat interface inside" },
    ],
    correctChoiceId: "a",
    weakConcept: "Cisco PAT configuration",
    explanation: "The overload keyword enables PAT using the specified outside interface address.",
  },
  {
    id: "nat-9",
    prompt: "Dual-stack hosts use NAT44 when:",
    choices: [
      { id: "a", text: "IPv4 traffic exits to the Internet from private IPv4 space" },
      { id: "b", text: "All IPv6 traffic is translated to MAC" },
      { id: "c", text: "DNS queries use TCP only" },
      { id: "d", text: "OSPF adjacencies form" },
    ],
    correctChoiceId: "a",
    weakConcept: "NAT44 use case",
    explanation: "NAT44 translates between private and public IPv4; IPv6 typically does not need NAT for global unicast.",
  },
  {
    id: "nat-10",
    prompt: "Hairpin NAT (NAT loopback) allows:",
    choices: [
      { id: "a", text: "Internal users to reach an internal server via its public DNS name" },
      { id: "b", text: "STP to run on WAN links" },
      { id: "c", text: "VLAN hopping prevention" },
      { id: "d", text: "DHCP relay without a helper address" },
    ],
    correctChoiceId: "a",
    weakConcept: "NAT hairpin / loopback",
    explanation: "Hairpin NAT lets inside hosts use the public FQDN of an internally hosted service.",
  },
];
