import type { ChoiceDrillItem } from "@/components/simulators/SimulatorRegistry";

export const STATIC_ROUTE_POOL: ChoiceDrillItem[] = [
  {
    id: "sr-1",
    prompt: "Router R1 must reach 10.20.0.0/16 via next-hop 192.168.1.2. Which command is correct?",
    choices: [
      { id: "a", text: "ip route 10.20.0.0 255.255.0.0 192.168.1.2" },
      { id: "b", text: "ip route 10.20.0.0 0.0.255.255 192.168.1.2" },
      { id: "c", text: "route static 10.20.0.0/16 gi0/0" },
      { id: "d", text: "ip default-network 10.20.0.0" },
    ],
    correctChoiceId: "a",
    weakConcept: "Cisco static route syntax",
    explanation: "Use network + subnet mask (dotted decimal) + next-hop IP.",
  },
  {
    id: "sr-2",
    prompt: "A default static route on Cisco IOS is written as:",
    choices: [
      { id: "a", text: "ip route 0.0.0.0 0.0.0.0 203.0.113.1" },
      { id: "b", text: "ip route default 203.0.113.1" },
      { id: "c", text: "default-route 0.0.0.0/0 203.0.113.1" },
      { id: "d", text: "ip static 0.0.0.0 255.255.255.255 203.0.113.1" },
    ],
    correctChoiceId: "a",
    weakConcept: "Default static route",
    explanation: "0.0.0.0/0 matches all destinations not in the routing table.",
  },
  {
    id: "sr-3",
    prompt: "Floating static route behavior:",
    choices: [
      { id: "a", text: "Higher AD than the primary route; used only when primary is absent" },
      { id: "b", text: "Always preferred over OSPF" },
      { id: "c", text: "Requires BGP multihop" },
      { id: "d", text: "Replaces default gateway on switches" },
    ],
    correctChoiceId: "a",
    weakConcept: "Floating static routes",
    explanation: "Set administrative distance higher (e.g. 200) so the route installs only if the primary fails.",
  },
  {
    id: "sr-4",
    prompt: "Static route via exit interface (no next-hop) is typical when:",
    choices: [
      { id: "a", text: "The link is point-to-point (e.g. serial /30)" },
      { id: "b", text: "Multiple next hops exist on Ethernet" },
      { id: "c", text: "OSPF is running on the LAN" },
      { id: "d", text: "VLANs are trunked" },
    ],
    correctChoiceId: "a",
    weakConcept: "Static route via interface",
    explanation: "On P2P links you may use ip route net mask Serial0/0/0 without a next-hop.",
  },
  {
    id: "sr-5",
    prompt: "Administrative distance of a directly connected route is:",
    choices: [
      { id: "a", text: "0" },
      { id: "b", text: "1" },
      { id: "c", text: "90" },
      { id: "d", text: "110" },
    ],
    correctChoiceId: "a",
    weakConcept: "Administrative distance",
    explanation: "Connected routes (AD 0) beat static (1), which beats OSPF (110), etc.",
  },
  {
    id: "sr-6",
    prompt: "Which static route sends traffic for a single host 192.168.50.10?",
    choices: [
      { id: "a", text: "ip route 192.168.50.10 255.255.255.255 10.0.0.1" },
      { id: "b", text: "ip route 192.168.50.0 255.255.255.0 10.0.0.1" },
      { id: "c", text: "ip host-route 192.168.50.10" },
      { id: "d", text: "ip route 192.168.50.10 0.0.0.255 10.0.0.1" },
    ],
    correctChoiceId: "a",
    weakConcept: "Host static route (/32)",
    explanation: "A /32 host route uses mask 255.255.255.255.",
  },
  {
    id: "sr-7",
    prompt: "Recursive lookup for a static route means:",
    choices: [
      { id: "a", text: "The router resolves the next-hop IP via another route in the table" },
      { id: "b", text: "STP recalculates the root bridge" },
      { id: "c", text: "DNS resolves the static route name" },
      { id: "d", text: "The static route replaces ARP" },
    ],
    correctChoiceId: "a",
    weakConcept: "Recursive next-hop resolution",
    explanation: "The next-hop must be reachable; the router looks up how to reach that IP.",
  },
  {
    id: "sr-8",
    prompt: "On a stub network with one WAN exit, the most common static route is:",
    choices: [
      { id: "a", text: "Default route to the ISP gateway" },
      { id: "b", text: "Static route for every public /24" },
      { id: "c", text: "Floating OSPF default only" },
      { id: "d", text: "Host route for DNS" },
    ],
    correctChoiceId: "a",
    weakConcept: "Stub network routing",
    explanation: "A single default route toward the ISP is typical for small edge routers.",
  },
  {
    id: "sr-9",
    prompt: "Static route AD on Cisco IOS defaults to:",
    choices: [
      { id: "a", text: "1" },
      { id: "b", text: "5" },
      { id: "c", text: "20" },
      { id: "d", text: "110" },
    ],
    correctChoiceId: "a",
    weakConcept: "Static route AD",
    explanation: "Static routes have AD 1 unless changed with the distance keyword.",
  },
  {
    id: "sr-10",
    prompt: "Which issue can cause a valid static route to not appear in the routing table?",
    choices: [
      { id: "a", text: "Next-hop is not reachable (no route to next-hop / interface down)" },
      { id: "b", text: "VLAN 1 is the native VLAN" },
      { id: "c", text: "DNS server unreachable" },
      { id: "d", text: "802.1Q tag present on access port" },
    ],
    correctChoiceId: "a",
    weakConcept: "Static route troubleshooting",
    explanation: "If the next-hop cannot be resolved or the egress interface is down, the static route stays inactive.",
  },
];
