import type { ChoiceDrillItem } from "@/components/simulators/SimulatorRegistry";

export const VLAN_TRUNK_POOL: ChoiceDrillItem[] = [
  {
    id: "vlan-1",
    prompt: "Which IEEE standard defines VLAN tagging on trunk ports?",
    choices: [
      { id: "a", text: "802.1Q" },
      { id: "b", text: "802.3" },
      { id: "c", text: "802.11" },
      { id: "d", text: "802.1X" },
    ],
    correctChoiceId: "a",
    weakConcept: "802.1Q VLAN tagging",
    explanation: "802.1Q inserts a 4-byte tag with VLAN ID on Ethernet frames crossing trunk links.",
  },
  {
    id: "vlan-2",
    prompt: "A switch port configured as an access port carries traffic for:",
    choices: [
      { id: "a", text: "One VLAN (untagged)" },
      { id: "b", text: "All VLANs (tagged)" },
      { id: "c", text: "Only the native VLAN (tagged)" },
      { id: "d", text: "VLAN 1 only, always tagged" },
    ],
    correctChoiceId: "a",
    weakConcept: "Access vs trunk ports",
    explanation: "Access ports belong to a single VLAN and send untagged frames to end devices.",
  },
  {
    id: "vlan-3",
    prompt: "On a Cisco trunk, untagged frames belong to the:",
    choices: [
      { id: "a", text: "Native VLAN" },
      { id: "b", text: "Management VLAN" },
      { id: "c", text: "Voice VLAN" },
      { id: "d", text: "Default VLAN 4094" },
    ],
    correctChoiceId: "a",
    weakConcept: "Native VLAN",
    explanation: "The native VLAN carries untagged traffic on a trunk; mismatched native VLANs break connectivity.",
  },
  {
    id: "vlan-4",
    prompt: "Which command puts interface Gi0/1 into VLAN 20 as an access port?",
    choices: [
      { id: "a", text: "switchport mode access\nswitchport access vlan 20" },
      { id: "b", text: "vlan 20\ninterface gi0/1" },
      { id: "c", text: "switchport trunk allowed vlan 20" },
      { id: "d", text: "access-vlan 20" },
    ],
    correctChoiceId: "a",
    weakConcept: "Access port configuration",
    explanation: "Set mode access, then assign the access VLAN.",
  },
  {
    id: "vlan-5",
    prompt: "DTP (Dynamic Trunking Protocol) can negotiate:",
    choices: [
      { id: "a", text: "Access or trunk mode between Cisco switches" },
      { id: "b", text: "VLAN pruning only on routers" },
      { id: "c", text: "802.1Q vs ISL on end hosts" },
      { id: "d", text: "Root bridge election" },
    ],
    correctChoiceId: "a",
    weakConcept: "DTP trunk negotiation",
    explanation: "DTP negotiates trunk/access on Cisco switch-to-switch links when not statically configured.",
  },
  {
    id: "vlan-6",
    prompt: "VLAN 1 on Cisco switches is:",
    choices: [
      { id: "a", text: "The default VLAN; cannot be deleted" },
      { id: "b", text: "Reserved for voice traffic only" },
      { id: "c", text: "Always the native VLAN and cannot be changed" },
      { id: "d", text: "Used only for routed SVI management" },
    ],
    correctChoiceId: "a",
    weakConcept: "Default VLAN 1",
    explanation: "VLAN 1 exists by default on Cisco gear; best practice is not to use it for user traffic.",
  },
  {
    id: "vlan-7",
    prompt: "Which trunk encapsulation is industry standard and supported on modern Cisco switches?",
    choices: [
      { id: "a", text: "802.1Q" },
      { id: "b", text: "ISL (only)" },
      { id: "c", text: "PPP" },
      { id: "d", text: "HDLC" },
    ],
    correctChoiceId: "a",
    weakConcept: "Trunk encapsulation",
    explanation: "802.1Q is the open standard; ISL is legacy Cisco proprietary.",
  },
  {
    id: "vlan-8",
    prompt: "Two switches connected via trunk with mismatched native VLANs will likely cause:",
    choices: [
      { id: "a", text: "Leaked untagged traffic into the wrong VLAN" },
      { id: "b", text: "Immediate STP root loss only" },
      { id: "c", text: "Automatic VLAN 1 shutdown" },
      { id: "d", text: "No effect if 802.1Q is used" },
    ],
    correctChoiceId: "a",
    weakConcept: "Native VLAN mismatch",
    explanation: "Untagged frames are placed into each side's native VLAN — if they differ, traffic lands in the wrong broadcast domain.",
  },
  {
    id: "vlan-9",
    prompt: "An SVI (Switch Virtual Interface) is used to:",
    choices: [
      { id: "a", text: "Route between VLANs at Layer 3 on a multilayer switch" },
      { id: "b", text: "Tag frames on access ports" },
      { id: "c", text: "Replace STP on trunk links" },
      { id: "d", text: "Encrypt VLAN traffic" },
    ],
    correctChoiceId: "a",
    weakConcept: "Inter-VLAN routing with SVI",
    explanation: "An SVI is a VLAN interface (e.g. interface vlan 10) used as the default gateway for that VLAN.",
  },
  {
    id: "vlan-10",
    prompt: "Which range is the normal usable VLAN ID range on Cisco switches?",
    choices: [
      { id: "a", text: "1–4094" },
      { id: "b", text: "0–255" },
      { id: "c", text: "1–1024 only" },
      { id: "d", text: "100–999" },
    ],
    correctChoiceId: "a",
    weakConcept: "VLAN ID range",
    explanation: "Standard VLAN IDs are 1–4094; 0 and 4095 are reserved.",
  },
];
