import type { ChoiceDrillItem } from "@/components/simulators/SimulatorRegistry";

export const WIRELESS_STANDARD_POOL: ChoiceDrillItem[] = [
  {
    id: "wifi-1",
    prompt: "802.11ax (Wi-Fi 6) primarily improves:",
    choices: [
      { id: "a", text: "Efficiency in dense environments (OFDMA, MU-MIMO)" },
      { id: "b", text: "Operation only on 2.4 GHz" },
      { id: "c", text: "Replacement of WPA3" },
      { id: "d", text: "Maximum range via 900 MHz" },
    ],
    correctChoiceId: "a",
    weakConcept: "802.11ax / Wi-Fi 6",
    explanation: "Wi-Fi 6 focuses on throughput per user in crowded AP environments.",
  },
  {
    id: "wifi-2",
    prompt: "802.11ac (Wi-Fi 5) operates primarily on:",
    choices: [
      { id: "a", text: "5 GHz band" },
      { id: "b", text: "2.4 GHz only" },
      { id: "c", text: "60 GHz only" },
      { id: "d", text: "900 MHz ISM" },
    ],
    correctChoiceId: "a",
    weakConcept: "802.11ac frequency",
    explanation: "802.11ac is 5 GHz only; 802.11n can use 2.4 or 5 GHz.",
  },
  {
    id: "wifi-3",
    prompt: "Which 802.11 standard introduced MIMO widely in consumer gear?",
    choices: [
      { id: "a", text: "802.11n" },
      { id: "b", text: "802.11a" },
      { id: "c", text: "802.11b" },
      { id: "d", text: "802.11 (original)" },
    ],
    correctChoiceId: "a",
    weakConcept: "802.11n MIMO",
    explanation: "802.11n added MIMO and channel bonding up to 40 MHz.",
  },
  {
    id: "wifi-4",
    prompt: "2.4 GHz Wi-Fi has how many non-overlapping 20 MHz channels (US)?",
    choices: [
      { id: "a", text: "3 (1, 6, 11)" },
      { id: "b", text: "12" },
      { id: "c", text: "23" },
      { id: "d", text: "1" },
    ],
    correctChoiceId: "a",
    weakConcept: "2.4 GHz channel planning",
    explanation: "Channels 1, 6, and 11 do not overlap in the 2.4 GHz band.",
  },
  {
    id: "wifi-5",
    prompt: "WPA3 improves over WPA2 mainly with:",
    choices: [
      { id: "a", text: "SAE (dragonfly) for stronger personal passphrase auth" },
      { id: "b", text: "WEP compatibility mode" },
      { id: "c", text: "Removal of AES encryption" },
      { id: "d", text: "Mandatory 802.1X on home networks" },
    ],
    correctChoiceId: "a",
    weakConcept: "WPA3 / SAE",
    explanation: "SAE resists offline dictionary attacks better than WPA2-PSK 4-way handshake alone.",
  },
  {
    id: "wifi-6",
    prompt: "802.11n (Wi-Fi 4) introduced which throughput feature?",
    choices: [
      { id: "a", text: "MIMO and optional 40 MHz channels" },
      { id: "b", text: "WEP-only encryption" },
      { id: "c", text: "6 GHz operation only" },
      { id: "d", text: "802.1X RADIUS authentication" },
    ],
    correctChoiceId: "a",
    weakConcept: "802.11n / Wi-Fi 4",
    explanation: "802.11n added MIMO and channel bonding up to 40 MHz — taught in the Wi-Fi generations lesson.",
  },
  {
    id: "wifi-7",
    prompt: "A wireless controller + lightweight AP architecture is called:",
    choices: [
      { id: "a", text: "Split MAC / LWAPP/CAPWAP model" },
      { id: "b", text: "Ad hoc IBSS only" },
      { id: "c", text: "Fat AP with no SSID" },
      { id: "d", text: "802.1X trunk mode" },
    ],
    correctChoiceId: "a",
    weakConcept: "Centralized WLAN architecture",
    explanation: "Thin APs tunnel to a WLC; control and data planes may be split.",
  },
  {
    id: "wifi-8",
    prompt: "Which factor most reduces 5 GHz range vs 2.4 GHz at same power?",
    choices: [
      { id: "a", text: "Higher frequency attenuates more through obstacles" },
      { id: "b", text: "5 GHz uses WEP only" },
      { id: "c", text: "5 GHz disables MIMO" },
      { id: "d", text: "2.4 GHz uses wider channels by default" },
    ],
    correctChoiceId: "a",
    weakConcept: "5 GHz vs 2.4 GHz propagation",
    explanation: "Higher frequencies penetrate walls less; 2.4 GHz travels farther but is more congested.",
  },
  {
    id: "wifi-9",
    prompt: "Roaming between APs with the same SSID relies on:",
    choices: [
      { id: "a", text: "Clients re-associating as signal moves between AP radios" },
      { id: "b", text: "Changing the BSSID to match the SSID" },
      { id: "c", text: "Disabling CSMA/CA on 5 GHz" },
      { id: "d", text: "Using WEP on every channel" },
    ],
    correctChoiceId: "a",
    weakConcept: "Wi-Fi roaming",
    explanation: "Same SSID across APs lets clients roam — taught in the roaming lesson card.",
  },
  {
    id: "wifi-10",
    prompt: "SSID is:",
    choices: [
      { id: "a", text: "The human-readable wireless network name" },
      { id: "b", text: "The BSSID of the switch" },
      { id: "c", text: "A VLAN tag on copper" },
      { id: "d", text: "The WPA pre-shared key" },
    ],
    correctChoiceId: "a",
    weakConcept: "SSID definition",
    explanation: "SSID identifies the WLAN; BSSID is the AP radio MAC.",
  },
];
