import type { StudyTip, TopicExperience } from "@/content/types";

/** Shown on many cards so the table sticks without a sticky UI (Phase 1). */
const BLOCK_TABLE: StudyTip = {
  title: "Block table",
  body: "/24→256 (254 usable) · /25→128 (126) · /26→64 (62) · /27→32 (30) · /28→16 (14) · /29→8 (6) · /30→4 (2).",
};

/** LES experience — pie-first mental model, find-the-block spine, binary deferred (Wave 1). */
export const SUBNETTING_EXPERIENCE: TopicExperience = {
  anchor: { type: "tcp-ip-stack" },
  screens: [
    {
      id: "intro-why",
      type: "hero",
      tcpLayer: 2,
      headline: "Why subnet a network?",
      body: "One large network wastes addresses and creates one big broadcast domain. Subnetting splits it into right-sized pieces — like giving each department its own section of the street instead of one giant block.",
      terms: [
        {
          id: "subnet",
          label: "Subnet",
          tier: "basics",
          shortDefinition:
            "A smaller slice of an IP network — devices in the same subnet share a network portion.",
        },
      ],
    },
    {
      id: "intro-bridge",
      type: "teach",
      tcpLayer: 2,
      headline: "Subnetting builds on IPv4.",
      body: "You already know network vs host portions and /24 masks from IPv4 addressing. Subnetting is the next step: dividing one address range into smaller slices.",
      terms: [
        {
          id: "mask",
          label: "Subnet mask",
          tier: "basics",
          shortDefinition:
            "Marks where the network portion ends and the host portion begins — e.g. /24 or 255.255.255.0.",
        },
      ],
    },
    {
      id: "neighborhood-pie",
      type: "analogy",
      tcpLayer: 2,
      headline: "One neighborhood — 256 addresses.",
      body: "Picture one /24 as a street with 256 houses — numbered .0 through .255 in the last octet. On 192.168.1.x, every device shares 192.168.1; only the last number changes. That last octet is your whole pie.",
      media: {
        kind: "subnet-pie",
        prefix: 24,
      },
    },
    {
      id: "split-four-sections",
      type: "teach",
      tcpLayer: 2,
      headline: "Split the street into four sections.",
      body: "The city assigns Sales, IT, HR, and Finance each their own section: .0–.63 · .64–.127 · .128–.191 · .192–.255. How many houses per section? 64. Four sections × 64 = 256. That four-way split is what /26 means.",
      media: {
        kind: "subnet-pie",
        prefix: 26,
      },
      studyTip: BLOCK_TABLE,
    },
    {
      id: "pie-halving",
      type: "teach",
      tcpLayer: 2,
      headline: "Slice the pie — watch it shrink.",
      body: "/24 = one whole pie (256). /25 = two halves. /26 = four quarters. /27 = eight slices. Keep slicing to /28, /29, /30. Every +1 on the slash cuts the slice in half. The totals always add up to 256.",
      media: {
        kind: "subnet-pie",
        prefix: 24,
        interactive: true,
        maxPrefix: 30,
      },
      studyTip: BLOCK_TABLE,
    },
    {
      id: "block-halving",
      type: "memory",
      tcpLayer: 2,
      headline: "The halving rule.",
      body: "Memorize the pattern before anything else: each +1 on the slash halves the slice size. /24=256 · /25=128 · /26=64 · /27=32 · /28=16 · /29=8 · /30=4.",
      studyTip: BLOCK_TABLE,
    },
    {
      id: "changing-octet",
      type: "teach",
      tcpLayer: 2,
      headline: "Gray out the first three octets.",
      body: "On CCNA-style problems (/24–/30), 192.168.1 stays fixed. The last octet only runs 0–255 — that is the whole /24 pie. Only that number changes. Look at .90 and ask which block of 0–255 it falls in.",
      media: {
        kind: "block-finder",
        ip: "192.168.1.90",
        prefix: 26,
        mode: "gray",
      },
    },
    {
      id: "which-box-90",
      type: "teach",
      tcpLayer: 2,
      headline: "Which box is 90 in?",
      body: "/26 → block size 64. List the slices: 0–63 · 64–127 · 128–191 · 192–255. Ninety is in 64–127. That is the whole problem — network and broadcast come later.",
      media: {
        kind: "block-finder",
        ip: "192.168.1.90",
        prefix: 26,
        mode: "interactive",
      },
    },
    {
      id: "block-check-90",
      type: "checkpoint",
      tcpLayer: 2,
      headline: "Which block contains .90?",
      checkpointQuestionId: "subnetting-q6",
    },
    {
      id: "prefix-what",
      type: "teach",
      tcpLayer: 2,
      headline: "What is the prefix?",
      body: "The prefix is the /x in CIDR notation — /24, /26, /28. CIDR (Classless Inter-Domain Routing) writes IP + size together: 192.168.1.0/26. The slash tells you how the pie was cut — /26 means four blocks of 64. Higher slash = smaller blocks = more subnets.",
      terms: [
        {
          id: "prefix",
          label: "Prefix",
          tier: "basics",
          shortDefinition:
            "The /x number — how many bits define the network. /26 → blocks of 64 addresses.",
        },
        {
          id: "cidr",
          label: "CIDR",
          tier: "basics",
          shortDefinition:
            "Classless Inter-Domain Routing — IP/prefix notation (e.g. 10.0.0.0/24) instead of rigid Class A/B/C sizes.",
        },
      ],
      studyTip: BLOCK_TABLE,
    },
    {
      id: "slice-is-block",
      type: "teach",
      tcpLayer: 2,
      headline: "Slice = block (exam language).",
      body: "The pie metaphor uses slice; CCNA and the field say block or subnet — same thing. A block is one subnet's address range (e.g. 64–127). Usable hosts live inside the block; the ends of the block are reserved — you'll name those soon.",
    },
    {
      id: "block-table",
      type: "memory",
      tcpLayer: 2,
      headline: "Block-size cheat table.",
      body: "Prefix → block size (total addresses in one block). /26 → 64 · /28 → 16. Usable host count comes once the ends of the block are defined. Skip /31 and /32 for now.",
      studyTip: BLOCK_TABLE,
    },
    {
      id: "block-first-rule",
      type: "hero",
      tcpLayer: 2,
      headline: "Find the block first.",
      body: "Every subnetting problem is the same question: which block does this IP live in? Find the block — the range in the changing octet — and the rest falls out once you know the block.",
      studyTip: BLOCK_TABLE,
    },
    {
      id: "nav-five-steps",
      type: "teach",
      tcpLayer: 2,
      headline: "Five steps — every problem.",
      body: "1) What is the prefix (/x)? 2) Block size — halve from /24 for each +1 on the slash (/26 → 64). 3) Which block contains the IP? 4) Network = first address in that block. 5) Broadcast = last address.",
      studyTip: {
        title: "Navigation, not math",
        body: "If you feel lost, you probably skipped step 3. Which block is the IP in?",
      },
    },
    {
      id: "which-box-45",
      type: "teach",
      tcpLayer: 2,
      headline: "Which block is 45 in?",
      body: "192.168.1.45/27 — block size 32. Blocks: 0–31 · 32–63 · 64–95 · 96–127… Forty-five is in 32–63. No formulas — just find the block.",
      media: {
        kind: "block-finder",
        ip: "192.168.1.45",
        prefix: 27,
        mode: "interactive",
      },
    },
    {
      id: "block-check-45",
      type: "checkpoint",
      tcpLayer: 2,
      headline: "Which block contains .45?",
      checkpointQuestionId: "subnetting-q7",
    },
    {
      id: "which-box-200",
      type: "teach",
      tcpLayer: 2,
      headline: "Which block is 200 in?",
      body: "192.168.1.200/28 — block size 16. Near 200, check 192–207 and 208–223. Two hundred is in 192–207. Lock the range first; names come after.",
      media: {
        kind: "block-finder",
        ip: "192.168.1.200",
        prefix: 28,
        mode: "interactive",
      },
    },
    {
      id: "block-check-200",
      type: "checkpoint",
      tcpLayer: 2,
      headline: "Which block contains .200?",
      checkpointQuestionId: "subnetting-q8",
    },
    {
      id: "network-addr",
      type: "teach",
      tcpLayer: 2,
      headline: "Network address = start of the block.",
      body: "Once you know the block, the network address is the first number in that range. In 64–127, the network is .64. You cannot assign it to a PC — it names the subnet.",
      terms: [
        {
          id: "network-addr",
          label: "Network address",
          tier: "basics",
          shortDefinition: "First address in the block — identifies the subnet, not a device.",
        },
      ],
    },
    {
      id: "broadcast-addr",
      type: "teach",
      tcpLayer: 2,
      headline: "Broadcast address = end of the block.",
      body: "The broadcast is the last address in the block — not the next subnet's start. In 64–127, broadcast is .127. Traffic to it reaches every device on that subnet. Also not assignable.",
      terms: [
        {
          id: "broadcast-addr",
          label: "Broadcast address",
          tier: "basics",
          shortDefinition: "Last address in the block — one below the next boundary.",
        },
      ],
    },
    {
      id: "usable-range",
      type: "teach",
      tcpLayer: 2,
      headline: "Usable hosts = inside the block.",
      body: "Assign PCs to addresses between network and broadcast. In 64–127: network .64 · first host .65 · last host .126 · broadcast .127. The ends are reserved.",
      media: {
        kind: "block-finder",
        ip: "192.168.1.90",
        prefix: 26,
        mode: "revealed",
      },
    },
    {
      id: "total-vs-usable",
      type: "misconception",
      tcpLayer: 2,
      headline: "Total vs usable addresses.",
      body: "Block size = total addresses in the block. Usable hosts = block size − 2 (network and broadcast reserved). /28 → block size 16 → 14 usable. Read whether the question asks total or assignable.",
      studyTip: BLOCK_TABLE,
    },
    {
      id: "total-check",
      type: "checkpoint",
      tcpLayer: 2,
      headline: "Quick check — /28 total",
      checkpointQuestionId: "subnetting-q4",
    },
    {
      id: "cheat-order",
      type: "teach",
      tcpLayer: 2,
      headline: "Full answer — seven steps.",
      body: "Prefix → block size → which block? → network → broadcast → first host (network + 1) → last host (broadcast − 1). Steps 1–3 are navigation. Steps 4–7 are naming what you already found.",
      studyTip: BLOCK_TABLE,
    },
    {
      id: "which-block-worked",
      type: "teach",
      tcpLayer: 2,
      headline: "Full walkthrough: 192.168.1.90/26.",
      body: "Prefix /26 → block 64. Which block? 90 is in 64–127. Network .64 · broadcast .127 · first host .65 · last host .126. Five steps — prefix, size, block, network, broadcast.",
      media: {
        kind: "block-finder",
        ip: "192.168.1.90",
        prefix: 26,
        mode: "revealed",
      },
    },
    {
      id: "worked-45-27",
      type: "teach",
      tcpLayer: 2,
      headline: "Full walkthrough: 192.168.1.45/27.",
      body: "/27 → block 32. 45 is in 32–63. Network .32 · broadcast .63 · usable .33–.62. Count the five steps — prefix, size, block, network, broadcast.",
      media: {
        kind: "block-finder",
        ip: "192.168.1.45",
        prefix: 27,
        mode: "revealed",
      },
    },
    {
      id: "worked-200-28",
      type: "teach",
      tcpLayer: 2,
      headline: "Full walkthrough: 192.168.1.200/28.",
      body: "/28 → block 16. 200 is in 192–207. Network .192 · broadcast .207 · usable .193–.206. Do not mix /28 slices with a whole /24 — lock the prefix first.",
      studyTip: BLOCK_TABLE,
      media: {
        kind: "block-finder",
        ip: "192.168.1.200",
        prefix: 28,
        mode: "revealed",
      },
    },
    {
      id: "hosts-check",
      type: "checkpoint",
      tcpLayer: 2,
      headline: "Quick check — /26 hosts",
      checkpointQuestionId: "subnetting-q1",
    },
    {
      id: "borrow-slice",
      type: "teach",
      tcpLayer: 2,
      headline: "Borrowing = more slices.",
      body: "Subnetting does not add addresses — it re-slices the same 256-address pie. Need more subnets? Cut smaller slices. Each cut doubles subnet count and halves slice size.",
      terms: [
        {
          id: "borrow",
          label: "Borrowing bits",
          tier: "basics",
          shortDefinition:
            "Use host bits as network bits to create more subnets from one block.",
        },
      ],
    },
    {
      id: "borrow-four-subnets",
      type: "teach",
      tcpLayer: 2,
      headline: "How many slices do you need?",
      body: "2 subnets → /25 (128 each). 4 subnets → /26 (64 each). 8 → /27. 16 → /28. From 192.168.1.0/24 into four /26s: .0/26 · .64/26 · .128/26 · .192/26.",
      studyTip: BLOCK_TABLE,
    },
    {
      id: "why-powers-of-two",
      type: "teach",
      tcpLayer: 2,
      headline: "Why always 2, 4, 8…?",
      body: "IPv4 addresses are binary — each bit is only 0 or 1. Borrow 1 bit → 2 subnets (2¹). Borrow 2 bits → 4 subnets (2²). Borrow 3 → 8 (2³). Subnet counts are always powers of 2 because bits only have two states.",
      studyTip: BLOCK_TABLE,
    },
    {
      id: "borrow-prefix-grow",
      type: "teach",
      tcpLayer: 2,
      headline: "Why /24 becomes /26.",
      body: "Goal: four equal subnets from one /24. Split once → 2 subnets (/25). Split again → 4 subnets. Two splits = borrow 2 host bits → prefix rises by 2: /24 + 2 = /26. Same 256 addresses — now four blocks of 64.",
      media: {
        kind: "flow",
        items: [
          { icon: "layers", label: "1 bit → 2 slices" },
          { icon: "layers", label: "2 bits → 4 slices" },
          { icon: "layers", label: "/24 + 2 = /26" },
        ],
      },
    },
    {
      id: "boundaries",
      type: "teach",
      tcpLayer: 2,
      headline: "Valid subnet starts only.",
      body: "A /26 slice starts at .0, .64, .128, or .192 — multiples of block size 64. .50 lives in the 0–63 slice and is a valid host. It cannot START a subnet because 50 is not a multiple of 64.",
      studyTip: BLOCK_TABLE,
      media: {
        kind: "icons",
        items: [
          { icon: "server", label: ".0" },
          { icon: "server", label: ".64" },
          { icon: "server", label: ".128" },
          { icon: "server", label: ".192" },
        ],
      },
    },
    {
      id: "anchor-jumps",
      type: "teach",
      tcpLayer: 2,
      headline: "Anchor jumps — skip long counting.",
      body: "For /28 (block 16), jump to anchors 0, 64, 128, 192 — then count by 16 inside that group only. Do not count 0, 16, 32… all the way to 240 every time.",
      studyTip: BLOCK_TABLE,
    },
    {
      id: "nearest-multiple",
      type: "teach",
      tcpLayer: 2,
      headline: "Find the block start (network).",
      body: "Network address = the first number of the block that contains the IP. For 200/28 (blocks of 16): valid starts are 0, 16, 32… 192, 208. Two hundred sits in 192–207 — network is .192, not .200. Walk backward to the block start.",
      media: {
        kind: "block-finder",
        ip: "192.168.1.200",
        prefix: 28,
        mode: "revealed",
      },
    },
    {
      id: "block-range-drill",
      type: "teach",
      tcpLayer: 2,
      headline: "Drill: find the slice.",
      body: "Practice slice only — no network or broadcast yet. Try each in your head, then continue for answers.",
      studyTip: {
        title: "Your turn",
        body: "73/28 → ? · 155/28 → ? · 201/28 → ? · 37/29 → ? · 222/27 → ?",
      },
    },
    {
      id: "block-range-answers",
      type: "teach",
      tcpLayer: 2,
      headline: "Drill answers.",
      body: "73/28 → 64–79 · 155/28 → 144–159 · 201/28 → 192–207 · 37/29 → 32–39 · 222/27 → 192–223. Once the slice is locked, network = first number and broadcast = last.",
    },
    {
      id: "broadcast-check",
      type: "checkpoint",
      tcpLayer: 2,
      headline: "Quick check — broadcast",
      checkpointQuestionId: "subnetting-q2",
    },
    {
      id: "vlsm-what",
      type: "teach",
      tcpLayer: 2,
      headline: "What is VLSM?",
      body: "Variable Length Subnet Masking = right-sized blocks carved from one parent — not one mask for every site. Sales gets /24, IT /26, WAN /30. Purpose: stop wasting addresses by giving each site only what it needs.",
      terms: [
        {
          id: "vlsm",
          label: "VLSM",
          tier: "basics",
          shortDefinition:
            "Variable Length Subnet Mask — mix /24, /26, /30 inside one allocation.",
        },
      ],
    },
    {
      id: "vlsm-not-same",
      type: "misconception",
      tcpLayer: 2,
      headline: "VLSM is not one address, many masks.",
      body: "Wrong: same network address, different prefixes. Right: separate blocks — each with its own network address, prefix, and range. No overlap.",
    },
    {
      id: "vlsm-size-math",
      type: "teach",
      tcpLayer: 2,
      headline: "VLSM — pick the prefix from host count.",
      body: "Usable hosts = block size − 2. Need 50 hosts? Add 2 for network + broadcast → need 52 slots → /26 (62 usable) fits; /27 (30) does not. Need 200? /24 (254). Always pick the smallest prefix that still fits.",
      studyTip: BLOCK_TABLE,
    },
    {
      id: "vlsm-allocate-order",
      type: "teach",
      tcpLayer: 2,
      headline: "VLSM — allocate biggest first.",
      body: "Start with the largest requirement and assign it the first aligned block in the parent. Each assignment consumes its range; the next subnet starts where the previous ended. Biggest-first avoids alignment traps that waste space.",
    },
    {
      id: "vlsm-parent-scope",
      type: "teach",
      tcpLayer: 2,
      headline: "/24 vs /22 — different pies.",
      body: "/24 uses one full last octet (0–255). /23 merges two /24s — third octet .0–.1, any fourth octet. /22 merges four /24s — third octet .0–.3. VLSM often starts with a bigger parent like /22, then carves smaller blocks inside.",
      media: {
        kind: "flow",
        items: [
          { icon: "layers", label: "/24 → one octet (0–255)" },
          { icon: "layers", label: "/23 → two /24 chunks" },
          { icon: "layers", label: "/22 → four /24 chunks" },
        ],
      },
    },
    {
      id: "vlsm-example",
      type: "teach",
      tcpLayer: 2,
      headline: "VLSM walkthrough — step by step.",
      body: "Parent: 192.168.0.0/22 (covers .0.0–.3.255). Sales needs 200 → /24 (254 usable) → 192.168.0.0/24. IT needs 50 → /26 (62 usable) → next spot 192.168.1.0/26. WAN needs 2 → /30 (2 usable) → 192.168.1.64/30. Each step: count hosts, pick prefix, assign next free block.",
      media: {
        kind: "flow",
        items: [
          { icon: "layers", label: "/22 parent pie" },
          { icon: "monitor", label: "Step 1: /24 Sales" },
          { icon: "server", label: "Step 2: /26 IT" },
          { icon: "router", label: "Step 3: /30 WAN" },
        ],
      },
    },
    {
      id: "vlsm-map",
      type: "teach",
      tcpLayer: 2,
      headline: "VLSM — see the leftover space.",
      body: "After three blocks, unused addresses remain in the parent /22 — that is normal. VLSM minimizes waste by sizing each block to fit the need. Nothing overlaps; each block has its own network address.",
      studyTip: {
        title: "Why not one /22 for everyone?",
        body: "One size wastes addresses — a /30 WAN link does not need 254 hosts. VLSM right-sizes each department.",
      },
    },
    {
      id: "vlsm-check",
      type: "checkpoint",
      tcpLayer: 2,
      headline: "Quick check — VLSM",
      checkpointQuestionId: "subnetting-q3",
    },
    {
      id: "binary-optional",
      type: "teach",
      tcpLayer: 2,
      headline: "Curious why the table works?",
      body: "Binary, masks, and 2^host_bits explain every number in the block table. You do not need that depth to subnet on the job or pass CCNA — but it helps when masks change.",
      laterLearn: [
        "Binary & masks (optional follow-up)",
        "Host bits = 32 − prefix",
        "256 − mask octet = block size",
      ],
    },
    {
      id: "binary-why-brief",
      type: "teach",
      tcpLayer: 2,
      headline: "Why /26 = 64 (optional).",
      body: "Step 1: 6 host bits (32 − 26 = 6) → 2^6 = 64 addresses. Step 2: halving works too — /24=256, +2 on slash → 64. Step 3: /26 mask ends in .192 (borrows 2 bits: 128+64); 256 − 192 = 64.",
      studyTip: {
        title: "Where does .192 come from?",
        body: "Borrow 2 bits from the left of the host portion → 11000000 = 128+64 = 192. Next card shows the full pattern for any prefix.",
      },
      terms: [
        {
          id: "block",
          label: "Block size",
          tier: "basics",
          shortDefinition:
            "Addresses per block in the changing octet — halve from /24 or use 2^host_bits.",
        },
      ],
    },
    {
      id: "borrow-from-left",
      type: "teach",
      tcpLayer: 2,
      headline: "Borrow from the left.",
      body: "/24 mask last octet = 00000000 (all host). Each borrowed bit becomes a 1 from the left: 1 bit → 10000000 (128, /25) · 2 bits → 11000000 (192, /26) · 3 bits → 11100000 (224, /27). Block size = 256 − mask octet.",
      studyTip: {
        title: "Keep going",
        body: "4 bits → 11110000 (240, /28) · 5 → 11111000 (248, /29) · 6 → 11111100 (252, /30). Always from the left — never skip bits.",
      },
      media: {
        kind: "flow",
        items: [
          { icon: "layers", label: "1 bit → .128 (/25)" },
          { icon: "layers", label: "2 bits → .192 (/26)" },
          { icon: "layers", label: "3 bits → .224 (/27)" },
        ],
      },
    },
    {
      id: "host-bits-bridge",
      type: "teach",
      tcpLayer: 2,
      headline: "Network & broadcast in binary.",
      body: "You already know: network = first address in the block, broadcast = last. In binary: network has all host bits set to 0 (lowest value); broadcast has all host bits set to 1 (highest). CCNA tests both views.",
    },
    {
      id: "network-check",
      type: "checkpoint",
      tcpLayer: 2,
      headline: "Quick check — network address",
      checkpointQuestionId: "subnetting-q5",
    },
    {
      id: "beyond-slash30",
      type: "teach",
      tcpLayer: 2,
      headline: "Beyond /24–/30.",
      body: "/0 through /32 are all valid prefixes. Smaller slash = bigger block (/8, /16, /22, /23). /22 and /23 cross octet boundaries — same find-the-slice logic, but the changing octet may not be the last one. /31 and /32 are special cases deferred for now.",
      media: {
        kind: "flow",
        items: [
          { icon: "layers", label: "/8 · /16 → huge parents" },
          { icon: "layers", label: "/22 · /23 → cross-octet" },
          { icon: "layers", label: "/24–/30 → this lesson" },
          { icon: "server", label: "/31 · /32 → later" },
        ],
      },
      studyTip: {
        title: "What comes later",
        body: "/22–/23 cross-octet math · /31 point-to-point links (RFC 3021) · /32 = one address (host routes, loopbacks).",
      },
      laterLearn: [
        "Cross-octet subnetting (/22, /23)",
        "/31 and /32 — different usable-host rules",
        "Binary & masks (optional follow-up)",
      ],
    },
    {
      id: "exam-strategy",
      type: "teach",
      tcpLayer: 2,
      headline: "Exam strategy.",
      body: "Prefix → block size → which block? → network → broadcast → hosts. Write the range before anything else. Broadcast is the last address in the block, not the last usable host.",
      studyTip: BLOCK_TABLE,
    },
    {
      id: "summary",
      type: "summary",
      tcpLayer: 2,
      headline: "Subnetting fundamentals covered.",
      body: "256 addresses → find your block → network and broadcast fall out. /24–/30 is the drill core; /22–/23 cross-octet and /31–/32 come later. Five steps: prefix, size, block, network, broadcast.",
    },
  ],
};
